var chinese ={
    "name":{
    	"version": "2.6",
		"date": "2018-12-14",
       	"name":"zh"
    },
	"_front": {
		"Cancel": "取消",
		"Confirm": "确认",
		"About_Us": "关于我们",
		"Account": "我的账户",
		"UP": "UP",
		"Libiray": "模型库",
		"Help": "帮助",
		"My_Account": "我的账户",
		"Setting": "设置",
		"Skin": "皮肤",
		"Language": "语言",
		"Current_Language": "当前语言：",
		"Printer": "打印机",
		"No_UP_printers_found": "打印机未连接",
		"Printer_Name_Cannot_Be_Empty": "打印机名称不能为空",
		"Failed_to_locate_WiFi": "wifi查找失败",
		"Set_Success": "设置成功",
		"Please_Enter_Password": "请输入密码",
		"Upgrade": "软件升级",
		"Current": "当前版本",
		"Your_System_is_UPtodate": "当前版本已是最新",
		"Remind_me_of_the_new_version": "有版本更新时请提醒我",
		"Update": "升级",
		"Privacy_Policy": "隐私声明",
		"privacy": "请查看 Tiertime 的隐私声明以了解有关如何使用发送到 Tiertime 的数据的详细信息 , 您可以选择是否对应用程序启用数据收集功能.",
		"Details": "查看详情",
		"Skin_Color": "界面颜色",
		"Model_Color": "模型颜色：",
		"Basic": "基础色：",
		"Login": "登录",
		"Username_or_Email": "用户名/邮箱",
		"Sign_In": "登录",
		"Sign_Up": "注册",
		"Forgot_Password": "忘记密码？",
		"Login_Failed": "登录失败",
		"User_Account_has_not_been_Activated": "账户未激活",
		"User_does_not_Existed": "账户不存在",
		"Password_is_Incorrect": "密码错误",
		"Please_enter_your_username_and_password": "请输入用户名和密码",
		"Please_enter_user_name": "请输入用户名",
		"Please_enter_your_password": "请输入密码",
		"Network_Problems_and_Please_Try_Later": "网络出问题了，请稍后再试",
		"Login_Timeout": "登录超时",
		"Printer_Management": "打印机管理",
		"Serial_Number": "设备sn号",
		"Activation_Status": "激活状态",
		"Binding_Status": "绑定状态",
		"Activate": "激活",
		"Activated": "已激活",
		"Bind": "绑定",
		"Unbind": "解除绑定",
		"Success": "成功",
		"Unbind_Successfully": "解绑成功",
		"Failed_to_Unbind": "解绑失败",
		"Binding_Successfully": "绑定成功",
		"Activation_Succeeded": "激活成功",
		"Sign_out": "退出当前账户",
		"Username": "用户名（3-20个字符，字母开头）",
		"Emailenter": "邮箱（请输入您的邮箱）",
		"Password": "密码（6-32个数字或字母）",
		"Confirm_Password": "确认密码（再次输入密码）",
		"Registration_means_you_agree_with": "注册表示您同意",
		"Tiertime_End_User_Agreement": "《太尔时代用户协议》",
		"Invalid_Username": "用户名输入不合法",
		"Invalid_Email_Address": "邮箱输入不合法",
		"Invalid_Password": "密码输入不合法",
		"Passwords_Do_Not_Match": "两次密码输入不一致",	
		"Registration_Successful": "注册成功",
		"Congratulations": "恭喜",
		"success_text": "注册成功，激活码已发送到您的邮箱，请点击激活",
		"Email": "邮箱",
		"Error": "错误",
		"Email_or_Username_Error": "用户名或邮箱错误",
		"An_email_to_reset_your_password_has_been_sent_to_your_email_address": "重置密码邮件发送成功",
		"Failed_to_Reset_Password": "重置密码失败",
		"Home": "主页",
		"Print": "打印",
		"Initialize_Printer": "初始化打印机",
		"Calibrate": "校准",
		"Maintenance": "维护",
		"Move": "移动",
		"Scale": "缩放",
		"More": "类别",
		"View": "视图",
		"Undo": "回退",
		"Auto_Place": "自动摆放",
		"Rotate": "旋转",
		"Mirror": "镜像",
		"Save_Model": "保存模型",
		"Reset_to_Default": "重置",
		"Fix_Errors": "修复",
		"Merge": "合并",
		"Delete": "删除",
		"Top_View": "顶视图",
		"Bottom_View": "底视图",
		"Back_View": "后视图",
		"Free_View": "自由视图",
		"Right_View": "右视图",
		"Front_View": "前视图",
		"Left_View": "左视图",
		"Wait_a_moment": "稍等片刻…",
		"Range_is_from": "只能输入",
		"No_Axis_Chosen": "没有选择轴向",
		"Add": "添加",
		"Add_Picture": "添加图片",
		"Add_Mode": "添加模型",
		"Saving": "保存中",
		"Printer_Setting": "打印设置",
		"Normal": "默认",
		"Layer_Thickness": "层片厚度：",
		"Infill": "填充方式：",
		"Quality": "质&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;量：",
		"Fine": "较好",
		"Fast": "较快",
		"Turbo": "极快",
		"Option": "选项",
		"Preference": "高级",
		"Dormancy": "休&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;眠：",
		"Preview": "打印预览",
		"Select_Saved_Slot": "选择保存的槽位",
		"Reprint": "重复打印",
		"Slot": "槽位",
		"Number": "序号",
		"Time": "时间",
		"Date": "日期",
		"Choose": "选&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;择：",
		"Part": "密闭",
		"Surface": "层&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;数：",
		"Angle": "角&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;度：",
		"Support": "支撑",
		"Dense": "层&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;数：",
		"Area": "面&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;积：",
		"Space": "间&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;隔：",
		"No_Raft": "无底座：",
		"No_Support": "无支撑：",
		"Stable_Support": "稳固支撑：",
		"Others": "其他",
		"Unsolid_Model": "非实体模型：",
		"Thin_Wall": "薄&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;壁：",
		"Preheat": "预&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;热：",
		"Default": "设置默认",
		"Calibration": "平台校准",
		"Platform_Calibration": "平台点位校准",
		"Manual": "手动校准",
		"Auto_Level": "自动补偿",
		"Reset": "重置",
		"Nozzle_Height": "喷嘴高度",
		"Set": "设置",
		"Nozzle_Detect": "自动对高",
		"Demo_Op": "手动对高",
		"Demo_Op_Over": "完成手动对高",
		"Set_nozzle_height_is": "设置喷嘴高度为:",
		"Compensation": "补偿",
		"Set_Nozzle_Height_as": "保存喷嘴高度为",
		"Extrude": "挤出",
		"Withdraw": "撤回",
		"Stop": "停止",
		"Material": "材料",
		"Weight": "重&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;量：",
		"Customized": "自定义",
		"Customized_Material": "自定义材料",
		"Name": "名称",
		"Nozzle": "喷嘴(℃)",
		"Platform": "底板(℃)",
		"Process": "操作",
		"Please_sign_in_your_account": "请登录您的账户",
		"Material_Name_Duplicated": "材料名称重复",
		"Only_7_Materials_Allowed": "自定义材料最多7个",
		"Fields_can_not_be_Empty": "填写不完整",
		"Stop_Printing": "停止打印",
		"Pause": "暂停打印",
		"Resume": "恢复打印",
		"Stop_Preview": "停止预览",
		"Time_Left": "剩余",
		"h": "h",
		"m": "m",
		"s": "s",
		"Slicing": "计算中 ",
		"Sending": "传输中 ",
		"offical_initerface": "官方材料",
		"series_number": "序列号：",
		"serial_password": "密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码：",
		"please_series_number": "请输入序列号",
		"My_model": "我的模型",
		"Public_model":"Moshop",
		"Self_model":"私有",
		"Save_model": "收藏",
		"Share_model": "发布",
		"Buy_model": "购买",
		"My_print": "我的打印机",
		"Find_all_print": "查看所有打印机",
		"User_number": "用户积分",
		"Change_password": "修改密码",
		"upload_model": "上传模型",
		"upload": "上传",
		"upload_list": "上传列表",
		"readmessage": "正在准备数据传输 ···",
		"All": "全部",
		"Free": "1积分",
		"Pay": ">1积分",
		"Model_parameter": "模型参数",
		"Model_Size": "模型大小",
		"Model_price": "模型积分",
		"Model_filder": "模型文件",
		"Print_count": "打印次数",
		"Model_buy": "购买",
		"Model_save": "收藏",
		"Model_al_save": "已收藏",
		"Model_download": "下载模型",
		"Model_deleat": "删除模型",
		"Model_desript": "模型描述",
		"Model_name": "模型名称",
		"Download_on": "下载",
		"Model_share": "分享",
		"Cancel_upload": "取消发布",
		"All_download": "全部下载",
		"All_open": "全部打开",
		"Model_attr": "模型属性",
		"Model_information": "模型信息",
		"Filepath": "文件路径：",
		"Size": "模型尺寸：",
		"Min_Size": "最小位置：",
		"Max_Size": "最大位置：",
		"Vertex_Number": "顶点数目：",
		"Facet_Number": "面片数目：",
		"Volume": "体积：",
		"Surface_Area": "表面积：",
		"Inch": "英寸",
		"Mm": "毫米",
		"Alerady_buy": "已购买",
		"Manage" : "管理",
		"Model_unit": "单位：",
		"Auto_height_end": "自动对高结束",
		"Model_upload": "发布",
		"Unlimited": "无限制",
		"Error_prompt": "发生错误",
		"Connection_failed": "连接失败",
		"User_and_password": "用户名和密码不能为空",
		"User_and_password_already": "用户名或邮箱已存在",
		"Calibration_failure_temp_hot": "校准失败，喷头温度过高",
		"Member_login_in_auto": "自动登录",
		"Model_list_nav": "导航",
		"Model_share_cancle":  "已取消",
		"Keep_on_download": "继续下载",
		"Model_preparing":"正在准备数据，不能关闭",
		"LatestVersion": "最新版本 V.",
		"Failed_to_bind": "绑定失败",
		"Custom_material_information_empty":"自定义材料信息不能为空",
		"Clear_cache": "清理缓存",
		"Clear_download_model": "清除已下载模型",
		"Clear_cache_file": "清除缓存文件",
		"Compensation_height": "补偿高度：",
		"Current_nozzle_height_print": "喷嘴高度",
		"Model_insert": "基础模型",
		"Advanced_print": "高级打印",
		"Pause_position": "暂停位置",
		"Pause_height": "高度",
		"Print_cao": "打印槽位",
		"Pause_print_exame": "输入需要暂停的高度（毫米）例如：7.6",
		"Model_audit": "审核中",
		"Model_re_publish": "重新发布",
		"Cancel_clear_up": "取消清理",
		"Clear_finish": "清理完成",
		"Nozzle_diameter": "喷嘴直径：",
		"Infill_wrap": "Shell",
		"Infill_surface": "Surface",
		"Infill_style1": "13%",
		"Infill_style2": "15%",
		"Infill_style3": "20%",
		"Infill_style4": "65%",
		"Infill_style5": "80%",
		"Infill_style6": "99%",
		"Manual_activation": "手动激活",
		"Manual_file": "请载入activeCode.act文件以激活打印机",
		"Copy_message": "复制信息到剪贴板",
		"Manual_fail": "从服务器返回激活码失败",
		"Manual_download": "载入",
		"Manual_connecting": "正在激活,请等待...",
		"Platform_leval": "水平校准",
		"Platform_vertival": "垂直校准",
		"Model_default_color": "默认色：",
		"Model_color_design": "编辑",
		"Manual_have_code": "如果已经有激活码,可以尝试",
		"Manual_copy_success": "复制成功",
		"Infinite_print_price": "无限次打印积分",
		"Once_print_price": "单次打印积分",
		"Model_print_price": "模型打印积分",
		"Print_infinite": "无限次",
		"Model_buy_times": "购买次数",
		"Manual_email": "如果您没有这个文件,您可以登录",
		"Model_publish_limited": "无限次打印价格必须高于单次打印价格",
		"Manual_pass_information": "复制以下信息:",
		"Manual_get_code":"获取激活文件ActiveCode.act,手动激活打印机",
		"Colud_Print":"正在使用云端参数打印",
		"Manual_active_login_font": "您可以登录",
		"Manual_get_code_select": "获取activeCode.act",
		"Manual_send_email": "发送以下信息到support@tiertime.com获取:",
		"Manual_select_hide": "收起",
		"Check_upload_ups":"错误：不能上传受保护的模型",
		"Model_Skin_Color":"默认模型颜色",
		"Easy_peel":"易于剥离：",
		"Email_or_password_Error":"请输入正确的邮箱/用户名和密码",
		"Model_count_number": "打印次数不能小于1",
		"Local_model": "本地",
		"Load_check": "加载选中",
		"Material_type": "类&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;型：",
		"Material_history": "历&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;史：",
		"Account_User_Already": "用户名已存在",
		"Account_Email_Already": "邮箱已存在",
		"ABS_Cloud_Print":"正在使用ABS云参数打印",
		"network_font_content":"网络设置",
		"network_fast_font":"Socket(Port:8016,8017)",
		"network_normal_font":"HTTPS(Port:443)",
		"Network_Problems_and_register":"注册超时",
		"Network_Problems_and_regpassword": "重置密码超时",
		"Network_Problems_and_exit": "退出当前账户超时",
		"password_input":"请输入",
		"password_password":"的密码",
		"choose_better_thrick":"选择0.2mm的喷嘴可以获得更好的打印质量",
		"stop_print_message":"确认停止？",
		"Platform_model": "模型校准",
		"Platform_axial": "XYZ轴向校准",
		"Axial": "轴向",
		"Axial_descript": "注释",
		"Axial_fact": "S1：理论值",
		"Axial_test": "M1：实际值",
		"Axial_alert_message": "理论值或实际值不能为0",
		"Choose_floor": "打印底板：",
		"wifi_high_setting":"高级设置",
		"Usb_connect_network": "连接",
		"Back": "返回",
		"Load_standrd_model": "加载校准模型",
		"version_description": "版本声明",
		"reading_print_parmes": "正在获取打印参数",
		"link_other_print": "连接其他打印机",
		"connect_print_by_ip": "要连接到打印机，请输入其IP地址和可选的打印机密码",
		"connect_other_network": "加入其他网络",
		"m1_and_s1": "m1与s1的值相差不可超过+-1",
		"circle_floor_state": "选面置底",
		"version_loading": "正在下载 ...",
		"model_radius": "半径：",
		"model_height": "高度：",
		"model_width": "宽度：",
		"model_length": "边长：",
		"model_long": "长度：",
		"model_parm_font": "模型参数",
		"network_type": "类&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;型：",
		"network_address": "IP：",
		"network_port": "端&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;口：",
		"network_user": "用户名：",
		"network_test": "测试",
		"network_nouse_agent": "不使用代理",
		"network_use_http": "HTTPS代理",
		"contour_linewidth": "轮廓线宽：",
		"height_button_font": "选择想要成为底部的模型面，然后点击“确定”",
		"loop_input_error": "输入范围为默认轮廓线宽的 -0.15 到 +0.25mm",
		"network_testing": "测试中...",
		"address_and_port":"地址或端口都不能为空",
		"Model_radius_limit": "外半径必须大于内半径",
		"forbiddrn_User_Login": "禁止用户登录，请联系我们",
		"model_cart": "分类",
		"input_model_cart": "请选择模型分类",
		"repeat_choose":"选择",
		"account_setting":"账户设置",
		"print_refresh": "刷新",
		"message_problem_type": "反馈问题的类型：",
		"software_problem": "软件问题",
		"printer_problem": "打印机故障",
		"print_quality": "打印质量",
		"limit_input": "还可输入",
		"message_font": "字",
		"message_email": "联系方式：",
		"printer_sn": "打印机序列号：",
		"message_load_img": "上传截图：",
		"please_load_img": "请上传不大于4M的图片",
		"please_input_sn": "请输入数字",
		"message_input_email":"请输入邮件",
		"message_looking": "浏览",
		"message_send": "发送",
		"problem_and_information": "问题描述：",
		"model_spcview": "显示模式",
		"model_pou": "切平面",
		"edit_parames": "参数",
		"edit_slide": "边数：",
		"top_radius": "顶半径：",
		"bottom_radius": "底半径：",
		"out_radius": "外半径：",
		"in_radius": "内半径：",
		"edit_points": "点数：",
		"edit_font": "字体：",
		"edit_text": "文本：",
		"model_edit_font": "模型编辑",
		"message_message": "反馈",
		"edit_slide_count": "边数输入的范围必须是3-12",
		"edit_slide_point": "点数输入的范围必须是5-30",
		"edit_top_botom": "底半径不能为0",
		"spc_one": "线框",
		"spc_two": "实体",
		"spc_thr": "透视",
		"spc_for": "实体和线框",
		"circle_to_floor": "放置底板",
		"message_send_succ": "发送成功",
		"message_send_fail": "发送失败",
		"message_sending": "发送中...",
		"input_correct_email": "请输入合法的邮箱地址",
		"upload_succ": "上传成功",
		"upload_fail": "上传失败",
		"model_reserze": "反转",
		"please_input_your_num": "联系方式和问题描述不可为空",
		"model_radius_star_limit": "外半径不能小于内半径",
		"circle_lock": "锁定比例",
		"print_repeat_error":"槽位中没有可重复打印的数据",
		"qr_code": "二维码",
		"qr_code_button": "生成二维码",
		"demo_opration_font1": "校准时请将校准片放在喷嘴与平台之间，点击+/-按钮调整对应点平台高度，移动校准片感觉有轻微阻力时该点调整完毕。",
		"demo_opration_font2": "喷嘴高度设置为",
		"demo_opration_font3": "校准成功!",
		"cancel_model_progress": "取消加载",
		"add_model_publish": "添加子模型",
		"publish_model_state": "状态",
		"input_upload_name": "请输入上传模型的名称",
		"exit_preview_status": "退出预览",
		"branch_normal_angle": "支撑角度",
		"branch_normal_point": "悬边/悬点",
		"branch_angle": "角度",
		"branch_button":"启用",
		"branch_state": "显示",
		"branch_radius": "半径",
		"branch_area": "面积",
		"branch_show": "显示支撑体",
		"branch_all": "显示全部",
		"branch_title": "对模型其他操作，可能会影响支撑",
		"branch_hide_model": "隐藏模型",
		"branch_length": "长度",
		"branch_pull": "拉伸",
		"branch_loading_font": "正在生成支撑,请稍后...",
		"branch_title_font": "支撑编辑",
		"branch_deleat_exit": "删除/退出",
		"easy_show_font": "简易模式",
		"save_branch_message": "确定要保留当前修改后的支撑？",
		"input_num": "送进比例",
		"cail_num": "校准值",
		"manual_setting": "手动设置：",
		"opa_save": "保存",
		"add_printer": "添加打印机",
		"add_all_printer": "所有打印机",
		"add_fic_printer": "虚拟打印机",
		"add_printer_ip": "通过IP添加打印机",
		"add_printer_close": "关闭",
		"wait_task": "等待分配任务",
		"print_list": "当前列表",
		"history_list": "历史列表",
		"print_num": "打印顺序",
		"print_status": "状态",
		"print_user": "任务发布者",
		"upload_time": "上传时间",
		"print_total_time": "打印总耗时",
		"print_opration": "操作",
		"exit_printer_task": "点击后删除并退出TASK模式",
		"ip_input_error": "输入内容不合法",
		"send_print_job": "发送",
		"input_ip_ad": "请输入IP地址",
		"repeat_choose_select": "重复打印被选中的",
		"clear_his_list":"清除历史列表",
		"repeat_num": "重复打印次数：",
		"ip_and_gate_error": "IP和Gate需要在同一个网段",
		"preview_and_save": "保存到文件",
		"task_group_head": "task组信息",
		"task_prepare": "等待",
		"task_fail": "失败",
		"task_finish": "完成",
		"no_add_printer": "暂无可添加打印机",
		"task_printing": "打印",
		"server_error": "服务器返回错误",
		"x5_floor": "底板",
		"x5_floor_set": "复位",
		"x5_auto_change": "更换",
		"x5_open": "开/关门",
		"x5_exit": "退出",
		"x5_edit": "编辑",
		"material_load": "导入",
		"nozzle_no_inviable_or_material_error":"打印机材料设置错误，或者喷嘴直径不匹配",
		"user_edit_1": "自定义1",
		"user_edit_2": "自定义2",
		"x5_Continuous_print_font":"连续打印：",
		"printer_not_connected": "打印机未连接",
		"contour_mode_font":"轮廓模式",
		"suspend_layer_font":"暂停层",
		"Warm":"加&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;热："
	},
	"print": {
		"PrinterStatus-1":"打印机未连接",
		"PrinterStatus0": "未初始化",
		"PrinterStatus1": "打印机准备就绪",
		"PrinterStatus2": "打印中",
		"PrinterStatus3": "暂停打印",
		"PrinterStatus4": "喷嘴错误",
		"PrinterStatus5": "运动系统错误",
		"PrinterStatus6": "打印完成",
		"PrinterStatus7": "打印被停止",
		"PrinterStatus8": "喷嘴温度过高",
		"PrinterStatus9": "喷嘴温度过低",
		"PrinterStatus10": "平台温度过高",
		"PrinterStatus11": "数据准备中",
		"PrinterStatus12": "数据准备失败",
		"PrinterStatus13": "tt_reverse_3",
		"PrinterStatus14": "tt_reverse_4",
		"PrinterStatus15": "系统上电",
		"PrinterStatus16": "SD卡错误",
		"PrinterStatus17": "SD卡写入错误",
		"PrinterStatus18": "SD卡读取错误",
		"PrinterStatus19": "保存打印数据至SD卡",
		"PrinterStatus20": "移动指令错误",
		"PrinterStatus21": "版权限制",
		"PrinterStatus22": "打印次数限制",
		"PrinterStatus23": "通讯错误",
		"PrinterStatus24": "系统进入错误状态",
		"PrinterStatus25": "打印底板跟换失败",
		"PrinterStatus26": "换板完成，插入新底板",
		"PrinterStatus27": "等待换新板",
		"PrinterStatus28": "维护，操作设备中",
		"PrinterStatus29": "无材料",
		"PrinterStatus30": "断丝",
		"ERROR": "发生错误",
		"ERROR: Task cannot be performed during printing": "错误：打印机运行中，不能进行此操作",
		"ERROR: Incorrect material": "错误：打印机材料设置错误",
		"ERROR: Printer status error": "错误：打印机状态错误",
		"ERROR: Printer connection error": "错误：打印机连接错误",
		"ERROR: Data transfer failure": "错误：传输打印数据失败",
		"ERROR: Printer is busy,please stop and try again": "错误：系统正忙，请停止后再试",
		"ERROR: Printer material shortage,still continue?": "错误：打印材料不足，是否继续打印？",
		"ERROR: Printer support material shortage,still continue?": "错误：支撑材料不足，是否继续打印？",
		"Correct range": "正确范围",
		"Repeat last print?": "确定重复打印吗？",
		"ERROR: Other error ": "错误：其他错误 ",
		"Language test": "当前语言为中文",
		"Are you sure to stop the print job?": "确定停止吗？",
		"Found a new version": "新版本更新内容，版本号",
		",download it immediately?": "，是否立即更新？",
		"[YES]: Update immediately": "[是]：立即更新",
		"[NO]: Remind me later": "[否]：下次通知我",
		"[CANCEL]: Switch off update reminder": "[取消]：不再提示更新",
		"Note: Download will be running in the background, after the completion of the notice": "注意：下载将在后台运行。 完成后，您将收到通知。",
		"Update": "升级",
		"No new version": "无新版本",
		"ERROR: Temperature is too high": "错误：温度过高",
		"ERROR: Sensor not connected": "传感器未连接",
		"ERROR: Calibration Failure": "错误：校准失败",
		"ERROR: Printer is busy": "错误：系统正忙",
		"Success,Please reset nozzle height before printing": "调平成功，请重新设置喷头高度后进行打印",
		"ERROR: Printer error": "错误：打印机错误",
		"Print: ": "预计时间：",
		"Material: ": "预计耗材：",
		"g": "克",
		"H": "小时",
		"M": "分钟",
		"S": "秒",
		"ERROR: Templete directory get error": "错误：临时文件路径获取失败",
		"ERROR: Create dir error": "错误：创建目录失败",
		"ERROR: Copy UpdateFile Error_APP": "错误：拷贝升级程序失败_APP",
		"ERROR: Copy UpdateFile Error_DLL": "错误：拷贝升级程序失败_DLL",
		"ERROR: Nozzleheight set error": "错误：喷头高度设置错误",
		"ERROR:Model does not exist": "错误：模型不存在",
		"Activation": "激活",
		"Please activate the printer in time to use the full printer functions": "请及时激活打印机从而使用完整的打印机功能",
		"Activation state error, need to return to the factory": "激活状态错误，请返厂",
		"OK": "确定",
		"CANCEL": "取消",
		"YES": "是",
		"NO": "否",
		"ABORT": "退出",
		"RETRY": "重试",
		"IGNORE": "忽略",
		"Save successful": "保存成功",
		"Save failed": "保存失败",
		"Downloading, please wait": "正在下载，请稍等片刻",
		",upgrade now?": ",立刻升级？",
		"Level data save error": "调平数据保存错误",
		"ERROR: Printer no response": "错误：打印机无响应",
		"ERROR: Printer password error": "错误：密码错误",
		"ERROR: Printer connected by other clients": "错误：打印机被占用",
		"ERROR: Printer none certification": "错误：打印机未认证",
		"Connection OK": "连接成功",
		"Connection Error": "连接失败",
		"Activation is successful, please restart the printer": "激活成功，请重新启动打印机",
		"Can not Save more than 4 millon facets model": "不能保存超过400万面片的模型",
		"No Model Selected": "没有选中的模型",
		"warning!": "警告!",
		"    Delete Selected Model?": "    是否删除选中模型?",
		"    Delete All Models?": "    是否删除全部模型?",
		"Please close the front door": "请关闭前门",
		"Model is too large! Can not Load": "模型过大！不能导入！",
		"Loading Failed": "模型载入失败！",
		"Print job stopped at ": "打印任务停在第",
		"th layer, resume the print?": "层，是否恢复打印?",
		"ERROR:  Can not resume the broken print job": "错误：无法恢复已停止的打印作业。",
		"ERROR: Data transfer failed, try again?": "错误：数据传输失败，是否重试？",
		"OpenGL Version Too Low! Check your Graphic Drivers!": "UP Studio支持OpenGL版本2.0或更高版本，请更新您的OpenGL驱动程序。",
		"ERROR: Printer SN Error": "错误：打印机序列号有问题",
		"ERROR: Unknow error": "错误：未知错误",
		"ERROR: Invalide activekey": "错误：激活码错误",
		"ERROR: No factory actived": "错误：不是工厂激活状态",
		"ERROR: The server failed to return the activation code": "错误：从服务器返回激活码失败",
		"ERROR: Failed to get the check code from the printer": "错误：从打印机得到校验码失败",
		"ERROR: Failed to obtain an active state": "错误：获得激活状态失败",
		"ERROR: Model out of print bound": "错误：模型超出打印范围。如果模型大于构建范围，请调整模型大小。如果模型高度超过喷嘴高度，请检查喷嘴高度。",
		"ERROR: Server connection failed": "错误：服务器连接失败",
		"ERROR: Verification Failed,Please download activation package": "错误: 校验失败，请下载校验文件",
		"ERROR: Temperature is low": "错误：喷头温度低",
		"Do you want to keep current model?": "是否保留当前模型?",
		"ERROR: Image read failed": "错误：图片读取失败",
        "Multiple": "多个",
        "ERROR：Please select the model you need to upload": "错误：请选取需要上传的模型",
        "Initialize_Printer": "初始化打印机",
        "ERROR: Material modification failure": "错误：材料修改失败",
        "Price":"价格",
		"Point":"积分",
		"Sure to buy":"确定购买吗",
		"ERROR: Upload Error": "错误：上传错误",
        "ERROR: Network Disconnection": "错误：网络断开",
        "ERROR: Cancel publish failure":"错误：取消发布失败",
        "The printer does not support this feature":"打印机不支持该功能",
        "Print finished, please take out the model":"打印完成，请取出模型",
        "Cancel":"取消",
		"Not Prompt":"不再提醒",
		"No material detected, please replace it":"未检测到材料，请更换",
		"ERROR: Publish failure":"错误：发布失败",
		"ERROR:Gcode failed to run":"Gcode运行失败",
		"Run File":"运行文件",
		"ERROR: Input Not Valid":"错误：输入无效",
		"Select active file":"选择激活文件",
		"ERROR: X1 Or X2 Input Error":"错误：错误：X1与X2的差值过大",
		"ERROR: Z Or H Input Error":"错误：请减小Z值或增大H值",
		"ERROR: Save Error":"错误：保存失败",
		"ERROR: User Not Login":"错误：用户未登录",
		"ERROR: Model validation failure":"错误：模型验证失败",
		"Can Not Open File!":"无法打开文件！",
		"Can Not Verify File!":"无法验证文件！",
		"User Does Not Match!":"用户不匹配！",
		"ERROR: Clear SD card error":"错误：清理SD卡错误",
		"Clear SD card ok":"清理SD卡成功",
		"Not finish":"传输未完成",
		"System not ready":"系统未准备好",
		"Null layer":"模型有空层",
		"Part material insufficient for the print job":"模型材料不足",
		"Support material insufficient for the print job":"支撑材料不足",
		"Fail to send cmd to printer":"发送cmd指令失败",
		"Printer error":"打印机错误",
		"Can not load buildstart program":"加载程序失败",
		"Lost WIFI packages":"wifi数据丢失",
		"Null temperature setting":"没有设置喷嘴和底板温度",
		"License verify failed":"许可证验证失败",
		"ERROR: Slicing error":"错误：分层错误",
		"Connection Success":"连接成功",
		"ERROR: Connection Failed":"错误：连接失败",
		"Unlimited": "无限制",
		"Keep_on_download": "继续下载",
		"Crashed. Do you upload error messages?":"程序异常，是否上传错误信息？",
		"ERROR: Printing,cannot stop heating":"错误：正在打印，不能停止加热",
		"Fatal Error":"致命错误",
		"Range":"输入范围:",
		"ERROR: File size must be less than 4MB":"错误：图片大小不可大于4MB",
		"Perf Board":"UP 多孔板",
		"UP Flex Board":"UP Flex板",
		"UP Glass Board":"UP 玻璃板",
		"Delete all printjob slot":"喷嘴高度已被更改。由于槽位中保存之前的喷嘴高度，无法正常打印，所以槽位中的所有内容已被删除！",
		"Warning: Improperly formatted G-code may damage the printer":"警告：不匹配的G代码可能会损坏打印机！",
		"Input Error":"输入错误",
		"Model_Size": "模型大小",
		"Print_Count": "打印次数",
		"SAVE":"保存",
		"Data Processing":"数据准备中",
		"Ready":"待发布",
		"Prepare Data":"准备数据",
		"Wating":"等待发布",
		"RePublish":"重新发布",
		"ERROR: Gcode printing is not compatible with firmware version 346 or lower":"固件版本低于或等于346暂不支持Gcode打印",
		"Clear SD?":"重置SD卡后，喷嘴高度、九点补偿值、模型校准值将清0，材料信息将变为默认值，旧打印机槽位将清0，是否确认重置？",
		"ERROR: Only allow one TSK file to be loaded at the same time":"错误：只允许同时打开一个TSK文件",
		"ERROR: Printer not found":"错误：未找到打印机",
		"ERROR: Printer Information Load Error":"错误：没有打印机信息",
		"ERROR: Only Load One TSK Model":"错误：只能单独预览一个tsk模型",
		"TT_ERROR_TASK_MISMATCH_DIA":"错误：喷嘴直径不匹配",
		"TT_ERROR_TASK_MISMATCH_MATERIAL":"错误：材料不匹配",
		"TT_ERROR_TASK_MISMATCH_PRINTER":"错误：打印机不匹配",
		"TT_ERROR_TASK_MISMATCH_PRINTER_TYPE":"错误：打印机型号不匹配",
		"TT_ERROR_TASK_MISMATCH_OVERSIZE":"错误：模型超出打印范围",
		"TT_ERROR_TASK_SHORTAGE_MATERIAL":"错误：打印材料不足",
		"TT_ERROR_PRINT_ENABLE_STATUS_NOT_PREPARED":"错误：打印机未准备就绪",
		"TT_ERROR_PRINT_ENABLE_DOOR_IS_OPENED":"错误：请关闭打印机前门",
		"TT_ERROR_PRINT_ENABLE_PRINTER_NOT_IDLE":"错误：打印机非闲置状态",
		"TT_ERROR_PRINT_ENABLE_NOZZLE_HEIGHT":"错误：打印机喷嘴高度错误",
		"TT_ERROR_LIST_JOB_NOT_FOUND":"错误：Task读取错误（Job未找到）",
		"TT_ERROR_LIST_TASK_NOT_FOUND":"错误：Task读取错误（Task未找到）",
		"TT_ERROR_LIST_TASK_READ_ERROR":"错误：Task读取错误（Task读取错误）",
		"TT_ERROR_PRINT_PRINT_DATA_LOST":"错误：打印数据丢失",
		"TT_ERROR_PRINT_PRINT_STATUS_NOT_PREPARE":"错误：打印机状态不是数据准备状态",
		"TT_ERROR_PRINT_PRINT_SEND_ERROR":"错误：命令发送失败，和CPU的通讯故障或其他原因",
		"TT_ERROR_PRINT_PRINT_PROGRAM_STOPED":"错误：运动程序停止",
		"TT_ERROR_PRINT_PRINT_USER_STOPED":"错误：用户停止打印",
		"TT_ERROR_PRINT_PRINT_UNKNOWN_ERROR":"错误：未知错误",
		"Please upgrade printer now":"请升级打印机，否则软件无法与打印机正常通信",
		"New Version":"发现新版本",
		"BaseBoard_Error_No_Board":"没有可用的底板！",
		"BaseBoard_Error_Door_Error":"舱门错误！",
		"BaseBoard_Error_Operate_Error":"更换底板操作失败，请重新检查后重试！",
		"BaseBoard_Error_Check_Error":"底板检测失败！",
		"BaseBoard_Error_Reset_Error":"底板复位失败！",
		"ERROR: Model doesn't match this printer":"错误：材料不匹配",
		"Please Touch Switch":"请先轻轻按压TrueTouch探头",
		"ERROR: Check Cetus Touch Switch":"错误：没有检测到探头",
		"Please Insert The Nozzle Dectect Card To Calibrate Nozzle Height":"请插入对高片进行手动调整",
		"MoveUp":"上升",
		"MoveDown":"下降",
		"Out of range":"超过调整范围",
		"ERROR: The upper limit of nozzle height has been reached":"错误：请检查喷嘴高度设置或校准开关",
		"ERROR: AutoCalibrateHeight Timeout":"错误：自动补偿超时",
		"Please disconnect current printer!":"当前连接的打印机断开失败，请先断开当前连接的打印机",
		"SEND OK":"传输完成"
	},
	"graphic": {
		"Filepath: ": "文件路径: ",
		"Size: ": "模型尺寸: ",
		"Min-Size: ": "最小位置: ",
		"Max-Size: ": "最大位置: ",
		"Vertex Number: ": "顶点数目: ",
		"Facet Number: ": "面片数目: ",
		"Volume: ": "体积: ",
		"Copying...": "模型复制中，请等待...",
		"Saveing...": "模型保存中，请等待...",
		"has scaled from inch unit to mm unit!": "模型过小，已放大25.4倍！",
		"Property": "属性",
		"Merge": "合并模型",
		"Copy": "复制",
		"Delete": "删除",
		"Delete All": "全部删除",
		"Select All": "全部选择",
		"UnSelect All": "全不选择",
		"Initialize View": "复原视图",
		"Rotate By Models Center": "绕模型中心旋转",
		"Exit": "退出",
		"app is not verified":"程序未校验",
		"The file is damaged": "文件已损坏",
		"current models contain protected model! can not do this operation!":"当前模型中包含受保护的模型！不能进行此操作！",
		"UnKnown ERROR!Please Contact TierTime!":"未知错误！请联系我们",
		"Copy Number: ": "复制个数:",
		"Copy Model": "复制模型",
		"1 model": "1 个模型",
		"2 model": "2 个模型",
		"3 model": "3 个模型",
		"4 model": "4 个模型",
		"5 model": "5 个模型",
		"6 model": "6 个模型",
		"7 model": "7 个模型",
		"8 model": "8 个模型",
		"custom": "自定义",
		"Voxelization": "体素化",
		"Edit":"编辑",
		"Voxel Size":"体素大小:",
		"models are too large(more than 4000000) to upload!":"失败，模型面片数超过400万！",
		"models are too large(more than 2000000) to upload!":"失败，模型面片数超过200万！",
		"TSKFileName: ":"文件名称：",  
		"TSKUserName: ":"用户名：", 
		"TSKTypeName: ":"适用的打印机：", 
		"TSKDIAMTER: ":"喷嘴直径：",   
		"TSKTHICK: ":"层厚：",     
		"TSKSIZE: ":"模型尺寸：",      
		"TSKMATERIAL: ":"打印材料：",  
		"TSKCOLORPause: ":"暂停层颜色：",
		"TSKCOLORSupport: ":"支撑颜色：",
		"TSKCOLORHatch: ":"填充颜色：",
		"TSKCOLORLoop: ":"轮廓颜色：" 
	},
	"image_front": {
		"_Model_Height": "模型高度：",
		"_Base_Height": "基底高度：",
		"_Style": "风格：",
		"_Model_Size": "模型大小：",
		"_Unit": "单位(mm)",
		"_Pen_Size": "画笔大小：",
		"_Pen_Color": "画笔颜色：",
		"_Pen_Type": "画笔种类：",
		"_Erase_Size": "橡皮擦大小：",
		"_Font": "字&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;体：",
		"_Font_Size": "文字大小：",
		"_Font_Color": "文字颜色：",
		"_Constrain": "等比例：",
		"_Tools": "工&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;具：",
		"_Setting": "设置",
		"_Previous": "上一步",
		"_Apply": "应用",
		"_Go_back": "返回",
		"_Pen": "画笔",
		"_Rubber": "橡皮",
		"_Text": "文字",
		"_Cut": "裁剪",
		"_Toggle_color": "黑白转换",
		"_choose_model_base": "选择基底：",
		"_image_image": "图片",
		"_image_loop": "灯罩",
		"_image_pic": "相框",
		"_image_relative": "相对"
	},
	"errormsg": {
        "0": "成功",
        "-1": "错误: 没有返回",
        "-2": "错误: 打印机通讯被锁定",
        "-3": "错误: 程序退出",
        "-4": "错误: 没有操作权限",
        "-5": "错误: 模型校验失败",
        "-6": "错误: 未知的打印机命令",
        "-100": "错误: 获取失败(JSONARRAY)",
        "-101": "错误: 获取失败(JSONINT)",
        "-102": "错误: 获取失败(JSON)",
        "-110": "错误: 版本号获取失败(JSON)",
        "-111": "错误: 升级信息获取失败(JSON)",
        "-112": "错误: 隐私设置失败(JSON)",
        "-113": "错误: BANNER获取失败(JSON)",
        "-114": "错误: 检测登陆失败(JSON)",
        "-115": "错误: 参数无效(JSON)",
        "-200": "错误: 读取配置文件层厚信息失败",
        "-201": "错误: 读取配置文件无内容",
        "-202": "错误: 读取配置文件无内容(JSON)",
        "-203": "错误: 写入配置文件无内容(JSON)",
        "-204": "错误: 读取配置文件失败(ITEM)",
        "-205": "错误: 读取配置文件失败(ROOT)",
        "-206": "错误: 读取配置文件失败(KEY)",
        "-207": "错误: 配置文件不存在",
        "-208": "错误: 配置文件只读",
        "-209": "错误: 配置文件无内容(JSON)",
        "-210": "错误: 写入配置文件超时",
        "-300": "错误: 加密文件打开失败",
        "-400": "错误: 模型不存在",
        "-401": "错误: 模型超出打印范围",
        "-402": "错误: 正在读取模型",
        "-500": "错误: 通讯失败",
        "-501": "错误: 通讯失败(LEN)",
        "-502": "错误: 开始传送文件失败",
        "-503": "错误: 正在传送文件失败",
        "-504": "错误: 结束传送文件失败",
        "-505": "错误: 通讯写入失败",
        "-506": "错误: 通讯读取失败",
        "-530": "错误: 打印机主板通讯错误(VID)",
        "-531": "错误: 打印机主板通讯错误(CLAIM)",
        "-560": "错误: 打印机数据获取失败(VIRTUALSD)",
        "-561": "错误: 打印机数据设置失败(VIRTUALSD)",
        "-562": "错误: 打印机数据新建失败(VIRTUALSD)",
        "-563": "错误: 打印机数据读取失败(VIRTUALSD)",
        "-600": "错误: 连接WIFI打印机 无匹配的SN号",
        "-601": "错误: 连接WIFI打印机 无匹配的打印机信息",
        "-602": "错误: 连接WIFI打印机 密码错误",
        "-603": "错误: 连接WIFI打印机 打印机被占用",
        "-604": "错误: 连接WIFI打印机 打印机无授权",
        "-605": "错误: 连接WIFI打印机 失败",
        "-606": "错误: 连接WIFI打印机 通讯失败",
        "-607": "错误: 连接WIFI打印机 SOCKET获取失败",
        "-608": "错误: 连接WIFI打印机 获取主机名称失败",
        "-609": "错误: 连接WIFI打印机 获取SN号失败",
        "-610": "错误: 设置静态地址失败",
        "-611": "错误: 获取自定义打印机列表失败",
        "-612": "错误: 连接路由器失败",
        "-613": "错误: 无效的IP",
        "-614": "错误: 无效的IP MASK",
        "-615": "错误: 无效的DNS",
        "-616": "错误: 无效的IP GATEWAY",
        "-617": "错误: 获取路由器失败",
        "-618": "错误: 获取打印机列表失败",
        "-619": "错误: 获取打印机列表失败 打印机状态错误",
        "-620": "错误: 获取新的打印机状态失败",
        "-621": "错误: 路由器名称获取失败",
        "-630": "错误: 网络服务初始化失败(ATTACH)",
        "-631": "错误: 网络服务初始化失败",
        "-632": "错误: 网络服务错误",
        "-633": "错误: 网络服务超时",
        "-634": "错误: 网络服务未响应",
        "-635": "错误: 网络服务设置失败",
        "-680": "错误: 无线网络设置超时",
        "-700": "错误: 获取USB打印机列表失败",
        "-710": "错误: 获取离线打印机列表失败",
        "-800": "错误: 打印机没有准备就绪",
        "-801": "错误: 请关闭前门",
        "-802": "错误: 不在打印状态",
        "-803": "错误: 不在暂停状态",
        "-804": "错误: SN号无效",
        "-805": "错误: 喷嘴高度超出范围",
        "-806": "错误: 获取打印机信息失败",
        "-807": "错误: 已连接打印机，无法建立新的连接",
        "-808": "错误: 打印机状态忙（正在打印），无法接受其他请求",
        "-809": "错误: 喷嘴温度过高",
        "-810": "错误: 到达高度上限",
        "-811": "错误: 打印机未连接",
        "-812": "错误: 打印机未断开",
        "-813": "错误: SD卡容量低",
        "-814": "错误: 校准探头检测失败",
        "-815": "错误: 打印机状态忙，无法接受其他请求",
        "-816": "错误: 打印机类型错误",
        "-817": "错误: 打印机主板错误",
        "-818": "错误: 打印机端口超时",
        "-900": "错误: 材料断裂",
        "-901": "错误: 材料不足",
        "-902": "错误: 删除的材料未找到",
        "-903": "错误: 保存的材料未找到",
        "-904": "错误: 获取材料温度失败",
        "-905": "错误: 材料读取失败",
        "-906": "错误: 当前材料读取失败",
        "-1000": "错误: TASK文件 喷嘴直径不匹配",
        "-1001": "错误: TASK文件 材料不匹配",
        "-1002": "错误: TASK文件 打印机SN号不匹配",
        "-1003": "错误: TASK文件 打印机类型不匹配",
        "-1004": "错误: TASK文件 成型空间不匹配",
        "-1005": "错误: TASK文件 文件未找到",
        "-1006": "错误: TASK文件 读取失败",
        "-1007": "错误: TASK文件 拷贝失败",
        "-1008": "错误: TASK文件 保存失败",
        "-1009": "错误: TASK文件 文件为空",
        "-1010": "错误: TASK文件 获取信息失败",
        "-1020": "错误: 多个TASK文件 材料类型不统一",
        "-1021": "错误: 多个TASK文件 喷嘴直径不统一",
        "-1022": "错误: 多个TASK文件 打印机SN号不统一",
        "-1023": "错误: 多个TASK文件 打印机类型不统一",
        "-1100": "错误: 打印列表读取失败(JOB)",
        "-1101": "错误: 打印列表任务未找到(JOB)",
        "-1102": "错误: 打印列表读取失败(TASK)",
        "-1103": "错误: 打印列表任务未找到(TASK)",
        "-1104": "错误: 打印列表添加任务失败(JOB)",
        "-1105": "错误: 打印列表为空(JOB)",
        "-1106": "错误: 打印任务上移失败(JOB)",
        "-1107": "错误: 打印任务下移失败(JOB)",
        "-1108": "错误: 打印任务正在打印，不能删除(JOB)",
        "-1109": "错误: 打印任务状态更新失败(JOB)",
        "-1130": "错误: 历史任务列表空",
        "-1131": "错误: 历史任务未找到",
        "-1200": "错误: 恢复打印超时",
        "-1201": "错误: 恢复打印发送命令失败",
        "-1202": "错误: 恢复打印失败",
        "-1300": "错误: 暂停打印超时",
        "-1301": "错误: 暂停打印发送命令失败",
        "-1302": "错误: 暂停打印失败",
        "-1400": "错误: 停止打印超时",
        "-1401": "错误: 停止打印发送命令失败",
        "-1402": "错误: 停止打印失败",
        "-1500": "错误: 打印数据丢失",
        "-1501": "错误: 打印机不是准备就绪状态",
        "-1502": "错误: 打印命令发送失败",
        "-1503": "错误: 打印机运动系统无法正常工作，请重启打印机",
        "-1504": "错误: 用户停止打印",
        "-1505": "错误: 打印失败",
        "-1506": "错误: 打印机状态忙（正在打印），无法接受其他请求",
        "-1520": "错误: 重复打印失败",
        "-1600": "错误: 传输失败(BLOCK SIZE)",
        "-1601": "错误: 传输失败(CRC)",
        "-1602": "错误: 用户停止传输",
        "-1603": "错误: 传输失败(ID)",
        "-1604": "错误: 传输失败(RESPONSE)",
        "-1605": "错误: 传输失败(CREATE)",
        "-1606": "错误: 传输失败(ZIP)",
        "-1607": "错误: 传输失败(OPEN)",
        "-1608": "错误: 传输失败(WRITE)",
        "-1700": "错误: 打印机状态忙（分层），无法接受其他请求",
        "-1701": "错误: 用户停止分层",
        "-1800": "错误: JOBMAKER运行失败",
        "-1801": "错误: JOBMAKER创建NC文件失败",
        "-1802": "错误: JOBMAKER删除旧NC文件失败",
        "-1803": "错误: JOBMAKER未准备就绪",
        "-1900": "错误: 对高传感器错误",
        "-1901": "错误: 喷嘴温度过高",
        "-1902": "错误: 对高超时",
        "-1903": "错误: 对高失败",
        "-1904": "错误: 本机型不支持对高操作",
        "-1910": "错误: 对高错误(ZTOMINZ)",
        "-1911": "错误: 对高错误(XYMOVE)",
        "-1912": "错误: 对高错误(RUNPROG)",
        "-1913": "错误: 对高错误(NORESPONSE)",
        "-1914": "错误: 对高错误(OVERMAXZ)",
        "-1915": "错误: 对高错误(ZBACKMINZ)",
        "-1916": "错误: 对高正在运行，无法重复操作",
        "-2000": "错误: 喷嘴温度过低(维护)",
        "-2001": "错误: 打印机状态错误(维护)",
        "-2002": "错误: 打印机正在进行维护，无法接受其他请求",
        "-2100": "错误: 喷嘴温度过高(九点调平)",
        "-2101": "错误: 调平传感器错误",
        "-2102": "错误: 调平失败",
        "-2103": "错误: 本机型不支持调平操作",
        "-2104": "错误: 没有底板",
        "-2105": "错误: 侧门错误",
        "-2106": "错误: 换板失败",
        "-2107": "错误: 复位底板失败",
        "-2108": "错误: 侧门检测失败",
        "-2109": "错误: 侧门失效",
        "-2200": "错误: 校准失败 X1或X2错误",
        "-2201": "错误: 校准失败 Z或H错误",
        "-2300": "错误: 数据库创建失败",
        "-2301": "错误: 数据库关闭失败",
        "-2302": "错误: 数据库更新数据失败",
        "-2303": "错误: 数据库设置尺寸失败",
        "-2304": "错误: 数据库删除记录失败",
        "-2305": "错误: 模型数据库读取失败(ALL)",
        "-2306": "错误: 模型数据库读取失败(ONE)",
        "-2307": "错误: BANNER数据库读取失败",
        "-2308": "错误: VIDEO数据库读取失败",
        "-2309": "错误: 参数数据库读取失败",
        "-2400": "错误: 激活打印机错误(服务器返回结果)",
        "-2401": "错误: 激活打印机错误(无数据)",
        "-2402": "错误: 激活打印机错误(用户停止)",
        "-2403": "错误: 错误的激活文件",
        "-2404": "错误: 激活错误(SN)",
        "-2405": "错误: 激活错误(USERID)",
        "-2406": "错误: 激活错误(CODE)",
        "-2407": "错误: 打印机已激活",
        "-2500": "错误: 只能加载一个TASK文件",
        "-2501": "错误: 加载的模型无效",
        "-2600": "错误: 正在分层,无法加载模型",
        "-2601": "错误: 正在预览,无法加载模型",
        "-2602": "错误: 打印机忙,无法加载模型",
        "-2700": "错误: 下载失败(创建文件)",
        "-2701": "错误: 下载失败(CURL)",
        "-2702": "错误: 图片下载失败(创建文件)",
        "-2703": "错误: 图片下载失败(CURL)",
        "-2704": "错误: 网络测试错误",
        "-2705": "错误: 网络通讯错误",
        "-2706": "错误: 网络通讯错误(POST)",
        "-2707": "错误: 网络通讯错误(POSTNEW)",
        "-2708": "错误: 上传错误",
        "-2800": "错误: THRIFT正确",
        "-2801": "错误: 验证登录失败",
        "-2802": "错误: 上传服务信息失败",
        "-2803": "错误: 获取打印参数失败",
        "-2804": "错误: 获取新版打印参数失败",
        "-2805": "错误: 获取材料信息失败",
        "-2806": "错误: 获取激活码失败",
        "-2807": "错误: 获取激活码失败(LITE)",
        "-2808": "错误: 激活失败",
        "-2809": "错误: 隐私设置失败",
        "-2810": "错误: 注册失败",
        "-2811": "错误: 登录失败",
        "-2812": "错误: 注销失败",
        "-2813": "错误: 获取当前连接打印机设备列表失败",
        "-2814": "错误: 获取已绑定打印机设备列表失败",
        "-2815": "错误: 重置密码失败",
        "-2816": "错误: 用户名校验失败",
        "-2817": "错误: 邮箱校验失败",
        "-2818": "错误: 解绑失败",
        "-2819": "错误: 绑定失败",
        "-2820": "错误: 获取底板信息失败",
        "-2821": "错误: 获取层厚信息失败",
        "-2822": "错误: 获取用户信息失败",
        "-2900": "错误: 反馈信息上传失败",
        "-2901": "错误: 崩溃信息上传失败",
        "-3000": "错误: 更新所有打印参数失败(RECEIVE)",
        "-3001": "错误: 更新所有打印参数失败(CHECK)",
        "-3002": "错误: 更新所有打印参数失败(MD5)",
        "-3003": "错误: 更新所有打印参数失败(JSON)",
        "-3004": "错误: 更新打印参数失败(RECEIVE)",
        "-3005": "错误: 更新打印参数失败(CHECK)",
        "-3006": "错误: 更新打印参数失败(MD5)",
        "-3007": "错误: 更新打印参数失败(JSON)",
        "-3100": "错误: 获取打印机空闲状态失败(CTRL)",
        "-3101": "错误: 等待打印机空闲超时(CTRL)",
        "-3102": "错误: 初始化打印机失败(CTRL)",
        "-3103": "错误: 获取运行结果超时(CTRL)",
        "-3104": "错误: 获取运行结果失败(CTRL)",
        "-3105": "错误: 获取打印信息失败(CTRL)",
        "-3106": "错误: 发送打印命令失败(CTRL)",
        "-3107": "错误: 发送打印命令失败(CTRL JOB)",
        "-3108": "错误: 打印TASK失败(CTRL)",
        "-3109": "错误: 激活失败 未知错误(CTRL)",
        "-3110": "错误: 激活失败 无效的激活码(CTRL)",
        "-3111": "错误: 激活失败 不是工厂激活状态(CTRL)",
        "-3112": "错误: 激活失败 错误的激活码(CTRL)",
        "-3113": "错误: 激活失败 获取校验码失败(CTRL)",
        "-3114": "错误: 获取打印机程序失败(CTRL)",
        "-3115": "错误: 连接打印机失败(CTRL)",
        "-3116": "错误: 获取TASK列表失败(CTRL)",
        "-3117": "错误: 获取打印机信息 通讯失败(CTRL)",
        "-3118": "错误: 获取打印机信息 SD卡错误(CTRL)",
        "-3119": "错误: 获取打印机信息 未知错误(CTRL)",
        "-3120": "错误: 保存信息到SD卡失败(CTRL)",
        "-3121": "错误: 设置端口参数失败(CTRL)",
        "-3122": "错误: 获取端口参数失败(CTRL)",
        "-3123": "错误: 获取电机位置失败(CTRL)",
        "-3124": "错误: 电机移动失败(CTRL)",
        "-3125": "错误: 电机移动到指定位置失败(CTRL)",
        "-3126": "错误: 电机停止失败(CTRL)",
        "-3127": "错误: 程序停止失败(CTRL)",
        "-3128": "错误: 停止所有打印机动作失败(CTRL)",
        "-3129": "错误: 恢复打印失败(CTRL)",
        "-3130": "错误: 暂停打印失败(CTRL)",
        "-3131": "错误: 获取程序运行状态失败(CTRL)",
        "-3132": "错误: 获取程序暂停状态失败(CTRL)",
        "-3133": "错误: 清空程序缓存失败(CTRL)",
        "-3134": "错误: 读取程序失败(CTRL)",
        "-3135": "错误: 打印机运动系统无法正常工作(CTRL)",
        "-3136": "错误: 底板加热失败(CTRL)",
        "-3137": "错误: 挤丝失败(CTRL)",
        "-3138": "错误: 撤丝失败(CTRL)",
        "-3139": "错误: 设置加热状态失败(CTRL)",
        "-3140": "错误: 获取加热状态失败(CTRL)",
        "-3141": "错误: 获取温度失败(CTRL)",
        "-3142": "错误: 设置温度失败(CTRL)",
        "-3143": "错误: 获取当前打印层失败(CTRL)",
        "-3144": "错误: 获取当前喷嘴高度失败(CTRL)",
        "-3145": "错误: 获取打印剩余时间失败(CTRL)",
        "-3146": "错误: 获取打印进度失败(CTRL)",
        "-3147": "错误: 获取打印机状态失败(CTRL)",
        "-3148": "错误: 设置打印机状态失败(CTRL)",
        "-3149": "错误: 保存程序到SD卡失败(CTRL)",
        "-3150": "错误: 从SD卡读取程序失败(CTRL)",
        "-3151": "错误: 设置Z轴精度失败(CTRL)",
        "-3152": "错误: 设置材料信息失败(CTRL)",
        "-3153": "错误: 获取全部打印机状态失败(CTRL)",
        "-3154": "错误: 连接USB打印机失败(CTRL)",
        "-3155": "错误: 设置WIFI模式失败(CTRL)",
        "-3156": "错误: 设置私有模式失败(CTRL)",
        "-3157": "错误: 获取私有模式失败(CTRL)",
        "-3158": "错误: 连接路由器失败(CTRL)",
        "-3159": "错误: 获取WIFI连接信息失败(CTRL)",
        "-3160": "错误: 获取打印机SN号失败(CTRL)",
        "-3161": "错误: 重置WIFI数据包失败(CTRL)",
        "-3162": "错误: 副喷头移动失败(CTRL)",
        "-3163": "错误: 获取激活状态失败(CTRL)",
        "-3164": "错误: 读取SD卡数据失败(CTRL)",
        "-3165": "错误: 写入SD卡数据失败(CTRL)",
        "-3166": "错误: 设置系统变量失败(CTRL)",
        "-3167": "错误: 获取系统变量失败(CTRL)",
        "-3168": "错误: 获取暂停层失败(CTRL)",
        "-3169": "错误: 恢复打印失败(CTRL)",
        "-3170": "错误: 获取总打印时间失败(CTRL)",
        "-3171": "错误: 设置系统方法失败(CTRL)",
        "-3172": "错误: GCODE运行失败(CTRL)",
        "-3173": "错误: GCODE文件打开失败(CTRL)",
        "-3174": "错误: GCODE文件无效(CTRL)",
        "-3175": "错误: 获取送丝检测器状态失败(CTRL)",
        "-3176": "错误: 没有材料(CTRL)",
        "-3177": "错误: 没有送丝检测器(CTRL)",
        "-3178": "错误: 设置打印机秘钥失败(CTRL)",
        "-3179": "错误: 获取授权串失败(CTRL)",
        "-3180": "错误: 获取授权密钥失败(CTRL)",
        "-3181": "错误: 获取打印机闲置状态失败(CTRL)",
        "-3501": "错误: 写入文件失败 打开失败",
        "-3502": "错误: 写入文件失败 写入失败",
        "-3503": "错误: 写入新文件失败 打开失败",
        "-3504": "错误: 写入新文件失败 写入失败",
        "-3505": "错误: 创建文件失败",
        "-3506": "错误: 创建文件夹失败",
        "-3507": "错误: 重命名失败",
        "-3508": "错误: 拷贝文件夹失败",
        "-3509": "错误: 删除文件夹失败",
        "-3510": "错误: 读取二进制文件失败",
        "-3511": "错误: 读取文件失败",
        "-3512": "错误: 获取文件路径失败",
        "-3513": "错误: 获取文件名与扩展名失败",
        "-3514": "错误: 获取文件尺寸失败",
        "-3515": "错误: USB存储器读取失败",
        "-3516": "错误: USB存储器内未找到升级文件",
        "-3517": "错误: 拷贝失败,无法打开源文件",
        "-3518": "错误: 拷贝失败,无法创建目标文件",
        "-3519": "错误: 拷贝失败,文件尺寸错误",
        "-3600": "错误: 解压文件错误 解压文件",
        "-3601": "错误: 解压文件错误 设置目标目录",
        "-3602": "错误: 打开解压文件错误",
        "-3603": "错误: 解压文件错误 获取解压文件",
        "-3604": "错误: 解压文件错误",
        "-3605": "错误: 解压文件错误 解压文件",
        "-3606": "错误: 解压文件错误 设置目标目录",
        "-3607": "错误: 打开解压文件错误",
        "-3608": "错误: 解压文件错误 获取解压文件",
        "-3609": "错误: 解压文件错误",
        "-3650": "错误: 创建压缩文件错误",
        "-3651": "错误: 添加压缩文件错误",
        "-3700": "错误: 保存BMP文件失败",
        "-3701": "错误: BMP转换JPG失败",
        "-3702": "错误: BMP转换JPG1000失败",
        "-3703": "错误: PNG读取失败",
        "-3800": "错误: 版本比较失败",
        "-3801": "错误: 获取版本号失败",
        "-3900": "错误: MD5校验 文件读取失败",
        "-3901": "错误: MD5校验 校验失败",
        "-4000": "错误: 选取文件失败",
        "-4001": "错误: 选取文件失败",
        "-4002": "错误: 选取文件夹失败",
        "-4003": "错误: 选取文件失败",
        "-4100": "错误: 注册表删除选项失败",
        "-4101": "错误: 注册表读取失败",
        "-4102": "错误: 注册表写入失败",
        "-4200": "错误: 磁盘容量错误",
        "-4201": "错误: 磁盘剩余容量错误"
    },
     "image": {}
}
