var chinese ={
    "name":{
    	"version": "2.0",
		"date": "2017-08-21",
       	"name":"zh"
    },
	"_front": {
		"Cancel": "取消",
		"Confirm": "确认",
		"About_Us": "关于我们",
		"Account": "我的账户",
		"UP": "UP",
		"Libiray": "模型库",
		"Help": "帮助",
		"My_Account": "我的账户",
		"Setting": "设置",
		"Skin": "皮肤",
		"Language": "语言",
		"Current_Language": "当前语言",
		"Printer": "打印机",
		"No_UP_printers_found": "打印机未连接",
		"Printer_Name_Cannot_Be_Empty": "打印机名称不能为空",
		"Failed_to_locate_WiFi": "wifi查找失败",
		"Set_Success": "设置成功",
		"Please_Enter_Password": "请输入密码",
		"Upgrade": "软件升级",
		"Current": "当前版本",
		"Your_System_is_UPtodate": "当前版本已是最新",
		"Remind_me_of_the_new_version": "有版本更新时请提醒我",
		"Update": "升级",
		"Privacy_Policy": "隐私声明",
		"privacy": "请查看 Tiertime 的隐私声明以了解有关如何使用发送到 Tiertime 的数据的详细信息 , 您可以选择是否对应用程序启用数据收集功能.",
		"Details": "查看详情",
		"Skin_Color": "界面颜色",
		"Model_Color": "模型颜色",
		"Basic": "基础色",
		"Login": "登录",
		"Username_or_Email": "用户名/邮箱",
		"Sign_In": "登录",
		"Sign_Up": "注册",
		"Forgot_Password": "忘记密码？",
		"Login_Failed": "登录失败",
		"User_Account_has_not_been_Activated": "账户未激活",
		"User_does_not_Existed": "账户不存在",
		"Password_is_Incorrect": "密码错误",
		"Please_enter_your_username_and_password": "请输入用户名和密码",
		"Please_enter_user_name": "请输入用户名",
		"Please_enter_your_password": "请输入密码",
		"Network_Problems_and_Please_Try_Later": "网络出问题了，请稍后再试",
		"Login_Timeout": "登录超时",
		"Printer_Management": "打印机管理",
		"Serial_Number": "设备sn号",
		"Activation_Status": "激活状态",
		"Binding_Status": "绑定状态",
		"Activate": "激活",
		"Activated": "已激活",
		"Bind": "绑定",
		"Unbind": "解除绑定",
		"Success": "成功",
		"Unbind_Successfully": "解绑成功",
		"Failed_to_Unbind": "解绑失败",
		"Binding_Successfully": "绑定成功",
		"Activation_Succeeded": "激活成功",
		"Sign_out": "退出当前账户",
		"Username": "用户名（3-20个字符，字母开头）",
		"Emailenter": "邮箱（请输入您的邮箱）",
		"Password": "密码（6-32个字符）",
		"Confirm_Password": "确认密码（再次输入密码）",
		"Registration_means_you_agree_with": "注册表示您同意",
		"Tiertime_End_User_Agreement": "《太尔时代用户协议》",
		"Invalid_Username": "用户名输入不合法",
		"Invalid_Email_Address": "邮箱输入不合法",
		"Invalid_Password": "密码输入不合法",
		"Passwords_Do_Not_Match": "两次密码输入不一致",	
		"Registration_Successful": "注册成功",
		"Congratulations": "恭喜",
		"success_text": "注册成功，激活码已发送到您的邮箱，请点击激活",
		"Email": "邮箱",
		"Error": "错误",
		"Email_or_Username_Error": "用户名或邮箱错误",
		"An_email_to_reset_your_password_has_been_sent_to_your_email_address": "重置密码邮件发送成功",
		"Failed_to_Reset_Password": "重置密码失败",
		"Home": "主页",
		"Import_Model_or_Image": "添加模型或图片",
		"Print": "打印",
		"Initialize_Printer": "初始化打印机",
		"Calibrate": "校准",
		"Maintenance": "维护",
		"Move": "移动",
		"Scale": "缩放",
		"More": "类别",
		"View": "视图",
		"Undo": "回退",
		"Auto_Place": "自动摆放",
		"Rotate": "旋转",
		"Mirror": "镜像",
		"Save_Model": "保存模型",
		"Reset_to_Default": "重置",
		"Fix_Errors": "修复",
		"Merge": "合并",
		"Delete": "删除",
		"Top_View": "顶视图",
		"Bottom_View": "底视图",
		"Back_View": "后视图",
		"Free_View": "自由视图",
		"Right_View": "右视图",
		"Front_View": "前视图",
		"Left_View": "左视图",
		"Wait_a_moment": "稍等片刻…",
		"Range_is_from": "只能输入",
		"No_Axis_Chosen": "没有选择轴向",
		"Add": "添加",
		"Add_Picture": "添加图片",
		"Add_Mode": "添加模型",
		"Saving": "保存中",
		"Printer_Setting": "打印设置",
		"Normal": "默认",
		"Layer_Thickness": "层片厚度",
		"Infill": "填充方式",
		"Quality": "质量",
		"Fine": "较好",
		"Fast": "较快",
		"Turbo": "极快",
		"Option": "选项",
		"Preference": "高级",
		"Dormancy": "休眠",
		"Preview": "打印预览",
		"Select_Saved_Slot": "选择保存的槽位",
		"Reprint": "重复打印",
		"Slot": "槽位",
		"Number": "序号",
		"Time": "时间",
		"Date": "日期",
		"Choose": "选择",
		"Part": "密闭",
		"Surface": "密闭层数",
		"Angle": "角度",
		"Support": "支撑",
		"Dense": "支撑层数",
		"Area": "支撑面积",
		"Space": "支撑间隔",
		"No_Raft": "无底座",
		"No_Support": "无支撑",
		"Stable_Support": "稳固支撑",
		"Others": "其他",
		"Unsolid_Model": "非实体模型",
		"Thin_Wall": "薄壁",
		"Preheat": "加热",
		"Default": "设置默认",
		"Calibration": "平台校准",
		"Platform_Calibration": "平台点位校准",
		"Manual": "手动校准",
		"Auto_Level": "自动补偿",
		"Reset": "重置",
		"Nozzle_Height": "喷嘴高度",
		"Set": "设置",
		"Nozzle_Detect": "自动对高",
		"Demo_Op": "演示操作",
		"Demo_Op_Over": "演示结束",
		"Set_nozzle_height_is": "设置喷嘴高度为:",
		"Compensation": "补偿",
		"Set_Nozzle_Height_as": "保存喷嘴高度为",
		"Extrude": "挤出",
		"Withdraw": "撤回",
		"Stop": "停止",
		"Material": "材料",
		"Weight": "重量",
		"Customized": "自定义",
		"Customized_Material": "自定义材料",
		"Name": "名称",
		"Nozzle": "喷嘴(℃)",
		"Platform": "底板(℃)",
		"Process": "操作",
		"Please_sign_in_your_account": "请登录您的账户",
		"Material_Name_Duplicated": "材料名称重复",
		"Only_7_Materials_Allowed": "自定义材料最多7个",
		"Fields_can_not_be_Empty": "填写不完整",
		"Stop_Printing": "停止打印",
		"Pause": "暂停打印",
		"Resume": "恢复打印",
		"Stop_Preview": "停止预览",
		"Time_Left": "剩余",
		"h": "h",
		"m": "m",
		"s": "s",
		"Slicing": "计算中 ",
		"Sending": "传输中 ",
		"offical_initerface": "官方材料",
		"series_number": "序列号",
		"serial_password": "密码",
		"please_series_number": "请输入序列号",
		"My_model": "我的模型",
		"Public_model":"Moshop",
		"Self_model":"私有",
		"Save_model": "收藏",
		"Share_model": "发布",
		"Buy_model": "购买",
		"My_print": "我的打印机",
		"Find_all_print": "查看所有打印机",
		"User_number": "用户积分",
		"Change_password": "修改密码",
		"upload_model": "上传模型",
		"upload": "上传",
		"upload_list": "上传列表",
		"readmessage": "正在准备数据传输 ···",
		"All": "全部",
		"Free": "1积分",
		"Pay": ">1积分",
		"Model_parameter": "模型参数",
		"Model_Size": "模型大小",
		"Model_price": "模型积分",
		"Model_filder": "模型文件",
		"Print_count": "打印次数",
		"Model_buy": "购买",
		"Model_save": "收藏",
		"Model_al_save": "已收藏",
		"Model_download": "下载模型",
		"Model_deleat": "删除模型",
		"Model_desript": "模型描述",
		"Model_name": "模型名称",
		"Download_on": "下载",
		"Model_share": "分享",
		"Cancel_upload": "取消发布",
		"All_download": "全部下载",
		"All_open": "全部打开",
		"Model_attr": "模型属性",
		"Model_information": "模型信息",
		"Filepath": "文件路径: ",
		"Size": "模型尺寸: ",
		"Min_Size": "最小位置: ",
		"Max_Size": "最大位置: ",
		"Vertex_Number": "顶点数目: ",
		"Facet_Number": "面片数目: ",
		"Volume": "体积:",
		"Surface_Area": "表面积:",
		"Inch": "英寸",
		"Mm": "毫米",
		"Alerady_buy": "已购买",
		"Manage" : "管理",
		"Model_unit": "单位:",
		"Auto_height_end": "自动对高结束",
		"Flex_plat": "麦拉片",
		"Ward_plat": "蜂窝板",
		"Model_upload": "发布",
		"Unlimited": "无限制",
		"Error_prompt": "发生错误",
		"Connection_failed": "连接失败",
		"User_and_password": "用户名和密码不能为空",
		"User_and_password_already": "用户名或邮箱已存在",
		"Calibration_failure_temp_hot": "校准失败，喷头温度过高",
		"Member_login_in_auto": "自动登录",
		"Model_list_nav": "导航",
		"Model_share_cancle":  "已取消",
		"Keep_on_download": "继续下载",
		"Model_preparing":"正在准备数据，不能关闭",
		"LatestVersion": "最新版本 V.",
		"Failed_to_bind": "绑定失败",
		"Custom_material_information_empty":"自定义材料信息不能为空",
		"Clear_cache": "清理缓存",
		"Clear_download_model": "清除已下载模型",
		"Clear_cache_file": "清除缓存文件",
		"Compensation_height": "补偿高度",
		"Current_nozzle_height_print": "喷嘴高度",
		"Model_insert": "模型插入",
		"Advanced_print": "高级打印",
		"Pause_position": "暂停位置",
		"Pause_height": "高度",
		"Print_cao": "打印槽位",
		"Pause_print_exame": "输入需要暂停的高度（毫米）例如：7.6",
		"Model_audit": "审核中",
		"Model_re_publish": "重新发布",
		"Cancel_clear_up": "取消清理",
		"Clear_finish": "清理完成",
		"Nozzle_diameter": "喷嘴直径",
		"Infill_wrap": "Shell",
		"Infill_surface": "Surface",
		"Infill_style1": "13%",
		"Infill_style2": "15%",
		"Infill_style3": "20%",
		"Infill_style4": "65%",
		"Infill_style5": "80%",
		"Infill_style6": "99%",
		"Manual_activation": "手动激活",
		"Manual_file": "请载入activeCode.act文件以激活打印机",
		"Copy_message": "复制信息到剪贴板",
		"Manual_fail": "从服务器返回激活码失败",
		"Manual_download": "载入",
		"Manual_connecting": "正在激活,请等待...",
		"Platform_leval": "水平校准",
		"Platform_vertival": "垂直校准",
		"Model_default_color": "默认色",
		"Model_color_design": "编辑",
		"Manual_have_code": "如果已经有激活码,可以尝试",
		"Manual_copy_success": "复制成功",
		"Infinite_print_price": "无限次打印积分",
		"Once_print_price": "单次打印积分",
		"Model_print_price": "模型打印积分",
		"Print_infinite": "无限次",
		"Model_buy_times": "购买次数",
		"Manual_email": "如果您没有这个文件,您可以登录",
		"Model_publish_limited": "无限次打印价格必须高于单次打印价格",
		"Manual_pass_information": "复制以下信息:",
		"Manual_get_code":"获取激活文件ActiveCode.act,手动激活打印机",
		"Colud_Print":"正在使用云端参数打印",
		"Manual_active_login_font": "您可以登录",
		"Manual_get_code_select": "获取activeCode.act",
		"Manual_send_email": "发送以下信息到zhangyh@tiertime.net获取:",
		"Manual_select_hide": "收起",
		"Check_upload_ups":"错误：不能上传受保护的模型",
		"Model_Skin_Color":"默认模型颜色",
		"Easy_peel":"易于剥离",
		"Email_or_password_Error":"请输入正确的邮箱/用户名和密码",
		"Model_count_number": "打印次数不能小于1",
		"Local_model": "本地",
		"Load_check": "加载选中",
		"Material_type": "类型",
		"Material_history": "历史",
		"Account_User_Already": "用户名已存在",
		"Account_Email_Already": "邮箱已存在",
		"ABS_Cloud_Print":"正在使用ABS云参数打印",
		"network_font_content":"网络设置",
		"network_fast_font":"快速链接",
		"network_normal_font":"普通链接",
		"Network_Problems_and_register":"注册超时",
		"Network_Problems_and_regpassword": "重置密码超时",
		"Network_Problems_and_exit": "退出当前账户超时",
		"password_input":"请输入",
		"password_password":"的密码",
		"choose_better_thrick":"选择0.2mm的喷嘴可以获得更好的打印质量",
		"stop_print_message":"确认停止？",
		"Platform_model": "模型校准",
		"Platform_axial": "XYZ轴向校准",
		"Axial": "轴向",
		"Axial_descript": "注释",
		"Axial_fact": "S1：理论值",
		"Axial_test": "M1：实际值",
		"Axial_alert_message": "理论值或实际值不能为0",
		"Choose_floor": "打印底板",
		"Ward_and_Flex": "蜂窝板+麦拉片",
		"Glass_plat": "4mm玻璃板",
		"wifi_high_setting":"高级设置",
		"Usb_connect_network": "连接",
		"Back": "返回",
		"Load_standrd_model": "加载校准模型",
		"version_description": "版本声明",
		"reading_print_parmes": "正在获取打印参数",
		"link_other_print": "连接其他打印机",
		"connect_print_by_ip": "要连接到打印机，请输入其IP地址和可选的打印机密码",
		"connect_other_network": "加入其他网络",
		"m1_and_s1": "m1与s1的值相差不可超过+-1",
		"circle_floor_state": "选面置底",
		"version_loading": "正在下载 ...",
		"model_radius": "半径：",
		"model_height": "高度：",
		"model_width": "宽度：",
		"model_length": "边长：",
		"model_long": "长度：",
		"model_parm_font": "模型参数",
		"network_type": "类型",
		"network_address": "IP",
		"network_port": "端口",
		"network_user": "用户名",
		"network_test": "测试",
		"network_nouse_agent": "不使用代理",
		"network_use_http": "HTTPS代理",
		"contour_linewidth": "轮廓线宽",
		"height_button_font": "选择想要成为底部的模型面，然后点击“确定”",
		"loop_input_error": "输入范围为默认轮廓线宽的 -0.15 到 +0.25mm",
		"network_testing": "测试中...",
		"address_and_port":"地址或端口都不能为空",
		"Model_radius_limit": "外半径必须大于内半径",
		"forbiddrn_User_Login": "禁止用户登录，请联系我们",
		"model_cart": "分类",
		"input_model_cart": "请选择模型分类",
		"account_setting":"账户设置",
		"print_refresh": "刷新",
		"message_problem_type": "反馈问题的类型：",
		"software_problem": "软件问题",
		"printer_problem": "打印机故障",
		"print_quality": "打印质量",
		"limit_input": "限制输入",
		"message_font": "字",
		"message_email": "联系方式：",
		"printer_sn": "打印机序列号：",
		"message_load_img": "上传截图：",
		"please_load_img": "请上传图片",
		"please_input_sn": "请输入",
		"message_looking": "浏览",
		"message_send": "发送",
		"problem_and_information": "问题和意见：",
		"model_spcview": "显示模式",
		"model_pou": "切平面",
		"edit_parames": "参数",
		"edit_slide": "边数：",
		"top_radius": "顶半径：",
		"bottom_radius": "底半径：",
		"out_radius": "外半径：",
		"in_radius": "内半径：",
		"edit_points": "点数：",
		"edit_font": "字体：",
		"edit_text": "文本：",
		"model_edit_font": "模型编辑",
		"message_message": "反馈",
		"edit_slide_count": "边数输入的范围必须是3-12",
		"edit_slide_point": "点数输入的范围必须是5-30",
		"edit_top_botom": "底半径和顶半径不能同时为0",
		"spc_one": "线框",
		"spc_two": "实体",
		"spc_thr": "透视",
		"spc_for": "实体和线框",
		"circle_to_floor": "一键置底",
		"message_send_succ": "发送成功",
		"message_send_fail": "发送失败",
		"message_sending": "发送中...",
		"input_correct_email": "请输入合法的邮箱地址",
		"upload_succ": "上传成功",
		"upload_fail": "上传失败",
		"model_reserze": "反转",
		"please_input_your_num": "请输入您的联系方式"
	},
	"print": {
		"PrinterStatus-1":"打印机未连接",
		"PrinterStatus0": "未初始化",
		"PrinterStatus1": "打印机准备就绪",
		"PrinterStatus2": "打印中",
		"PrinterStatus3": "暂停打印",
		"PrinterStatus4": "喷嘴错误",
		"PrinterStatus5": "运动系统错误",
		"PrinterStatus6": "打印完成",
		"PrinterStatus7": "打印被停止",
		"PrinterStatus8": "喷嘴温度过高",
		"PrinterStatus9": "喷嘴温度过低",
		"PrinterStatus10": "平台温度过高",
		"PrinterStatus11": "tt_reverse_1",
		"PrinterStatus12": "tt_reverse_2",
		"PrinterStatus13": "tt_reverse_3",
		"PrinterStatus14": "tt_reverse_4",
		"PrinterStatus15": "系统上电",
		"PrinterStatus16": "SD卡错误",
		"PrinterStatus17": "SD卡写入错误",
		"PrinterStatus18": "SD卡读取错误",
		"PrinterStatus19": "保存打印数据至SD卡",
		"PrinterStatus20": "移动指令错误",
		"PrinterStatus21": "版权限制",
		"PrinterStatus22": "打印次数限制",
		"PrinterStatus23": "通讯错误",
		"ERROR": "发生错误",
		"ERROR: Task cannot be performed during printing": "错误：打印机运行中，不能进行此操作",
		"ERROR: Incorrect material": "错误：打印机材料设置错误",
		"ERROR: Printer status error": "错误：打印机状态错误",
		"ERROR: Printer connection error": "错误：打印机连接错误",
		"ERROR: Data transfer failure": "错误：传输打印数据失败",
		"ERROR: Printer is busy,please stop and try again": "错误：系统正忙，请停止后再试",
		"ERROR: Printer material shortage,still continue?": "错误：打印材料不足，是否继续打印？",
		"ERROR: Printer support material shortage,still continue?": "错误：支撑材料不足，是否继续打印？",
		"Correct range": "正确范围",
		"Repeat last print?": "确定重复打印吗？",
		"ERROR: Other error ": "错误：其他错误 ",
		"Language test": "当前语言为中文",
		"Are you sure to stop the print job?": "确定停止吗？",
		"Found a new version": "发现新版本",
		",download it immediately?": "，是否立即更新？",
		"[YES]: Update immediately": "[是]：立即更新",
		"[NO]: Remind me later": "[否]：下次通知我",
		"[CANCEL]: Switch off update reminder": "[取消]：不再提示更新",
		"Note: Download will be running in the background, after the completion of the notice": "注意：下载将在后台运行。 完成后，您将收到通知。",
		"Update": "升级",
		"No new version": "无新版本",
		"ERROR: Temperature is too high": "错误：温度过高",
		"ERROR: Sensor not connected": "传感器未连接",
		"ERROR: Calibration Failure": "错误：校准失败",
		"ERROR: Printer is busy": "错误：系统正忙",
		"Success，Please reset nozzle height before printing": "调平成功，请重新设置喷头高度后进行打印",
		"ERROR: Printer error": "错误：打印机错误",
		"Print: ": "打印时间：",
		"Material: ": "耗费材料：",
		"g": "克",
		"H": "小时",
		"M": "分钟",
		"S": "秒",
		"ERROR: Templete directory get error": "错误：临时文件路径获取失败",
		"ERROR: Create dir error": "错误：创建目录失败",
		"ERROR: Copy UpdateFile Error_APP": "错误：拷贝升级程序失败_APP",
		"ERROR: Copy UpdateFile Error_DLL": "错误：拷贝升级程序失败_DLL",
		"ERROR: Nozzleheight set error": "错误：喷头高度设置错误",
		"ERROR:Model does not exist": "错误：模型不存在",
		"Activation": "激活",
		"Please activate the printer in time to use the full printer functions": "请及时激活打印机从而使用完整的打印机功能",
		"Activation state error, need to return to the factory": "激活状态错误，请返厂",
		"OK": "确定",
		"CANCEL": "取消",
		"YES": "是",
		"NO": "否",
		"ABORT": "退出",
		"RETRY": "重试",
		"IGNORE": "忽略",
		"Save successful": "保存成功",
		"Save failed": "保存失败",
		"Downloading, please wait": "正在下载，请稍等片刻",
		",upgrade now?": ",立刻升级？",
		"Level data save error": "调平数据保存错误",
		"ERROR: Printer no response": "错误：打印机无响应",
		"ERROR: Printer password error": "错误：密码错误",
		"ERROR: Printer connected by other clients": "错误：打印机被占用",
		"ERROR: Printer none certification": "错误：打印机未认证",
		"Connection OK": "连接成功",
		"Connection Error": "连接失败",
		"Activation is successful, please restart the printer": "激活成功，请重新启动打印机",
		"Can not Save more than 4 millon facets model": "不能保存超过400万面片的模型",
		"No Model Selected": "没有选中的模型",
		"warning!": "警告!",
		"    Delete Selected Model?": "    是否删除选中模型?",
		"    Delete All Models?": "    是否删除全部模型?",
		"Please close the front door": "请关闭前门",
		"Model is too large! Can not Load": "模型过大！不能导入！",
		"Loading Failed": "模型载入失败！",
		"Print job stopped at ": "打印任务停在第",
		"th layer, resume the print?": "层，是否恢复打印?",
		"ERROR:  Can not resume the broken print job": "错误：无法恢复已停止的打印作业。",
		"ERROR: Data transfer failed, try again?": "错误：数据传输失败，是否重试？",
		"OpenGL Version Too Low! Check your Graphic Drivers!": "OpenGL 版本过低，请更新显卡驱动",
		"ERROR: Printer SN Error": "错误：打印机序列号有问题",
		"ERROR: Unknow error": "错误：未知错误",
		"ERROR: Invalide activekey": "错误：激活码错误",
		"ERROR: No factory actived": "错误：不是工厂激活状态",
		"ERROR: The server failed to return the activation code": "错误：从服务器返回激活码失败",
		"ERROR: Failed to get the check code from the printer": "错误：从打印机得到校验码失败",
		"ERROR: Failed to obtain an active state": "错误：获得激活状态失败",
		"ERROR: Model out of print bound": "错误：模型超出打印范围",
		"ERROR: Server connection failed": "错误：服务器连接失败",
		"ERROR: Verification Failed,Please download activation package": "错误: 校验失败，请下载校验文件",
		"ERROR: Temperature is low": "错误：喷头温度低",
		"Do you want to keep current model?": "是否保留当前模型?",
		"ERROR: Image read failed": "错误：图片读取失败",
        "Multiple": "多个",
        "ERROR：Please select the model you need to upload": "错误：请选取需要上传的模型",
        "Initialize_Printer": "初始化打印机",
        "ERROR: Material modification failure": "错误：材料修改失败",
        "Price":"价格",
		"Point":"积分",
		"Sure to buy":"确定购买吗",
		"ERROR: Upload Error": "错误：上传错误",
        "ERROR: Network Disconnection": "错误：网络断开",
        "ERROR: Cancel publish failure":"错误：取消发布失败",
        "The printer does not support this feature":"打印机不支持该功能",
        "Print finished, please take out the model":"打印完成，请取出模型",
        "Cancel":"取消",
		"Not Prompt":"不再提醒",
		"No material detected, please replace it":"未检测到材料，请更换",
		"ERROR: Publish failure":"发布失败",
		"ERROR:Gcode failed to run":"Gcode运行失败",
		"Run File":"运行文件",
		"ERROR: Input Not Valid":"错误：输入无效",
		"Select active file":"选择激活文件",
		"ERROR: X1 Or X2 Input Error":"错误：X1或X2输入错误",
		"ERROR: Z Or H Input Error":"错误：Z或H输入错误",
		"ERROR: Save Error":"错误：保存失败",
		"ERROR: User Not Login":"错误：用户未登录",
		"ERROR: Model validation failure":"错误：模型验证失败",
		"Can Not Open File!":"无法打开文件！",
		"Can Not Verify File!":"无法验证文件！",
		"User Does Not Match!":"用户不匹配！",
		"ERROR: Clear SD card error":"错误：清理SD卡错误",
		"Clear SD card ok":"清理SD卡成功",
		"Not finish":"传输未完成",
		"System not ready":"系统未准备好",
		"Null layer":"模型有空层",
		"Part material insufficient for the print job":"模型材料不足",
		"Support material insufficient for the print job":"支撑材料不足",
		"Fail to send cmd to printer":"发送cmd指令失败",
		"Printer error":"打印机错误",
		"Can not load buildstart program":"加载程序失败",
		"Lost WIFI packages":"wifi数据丢失",
		"Null temperature setting":"没有设置喷嘴和底板温度",
		"License verify failed":"许可证验证失败",
		"ERROR: Slicing error":"错误：分层错误",
		"Connection Success":"连接成功",
		"ERROR: Connection Failed":"错误：连接失败",
		"Unlimited": "无限制",
		"Keep_on_download": "继续下载",
		"ERROR: Feedback ERROR":"错误：意见反馈提交失败",
		"Crashed. Do you upload error messages?":"程序异常，是否上传错误信息？",
		"ERROR: Printing,cannot stop heating":"错误：正在打印，不能停止加热",
		"Fatal Error":"致命错误"
	},
	"graphic": {
		"Invalid":"无效输入",
		"Filepath: ": "文件路径: ",
		"Size: ": "模型尺寸: ",
		"Min-Size: ": "最小位置: ",
		"Max-Size: ": "最大位置: ",
		"Vertex Number: ": "顶点数目: ",
		"Facet Number: ": "面片数目: ",
		"Volume: ": "体积: ",
		"Copying...": "模型复制中，请等待...",
		"Saveing...": "模型保存中，请等待...",
		"has scaled from inch unit to mm unit!": "模型过小，已放大25.4倍！",
		"Property": "属性",
		"Merge": "合并模型",
		"Copy": "复制",
		"Delete": "删除",
		"Delete All": "全部删除",
		"Select All": "全部选择",
		"UnSelect All": "全不选择",
		"Initialize View": "复原视图",
		"Rotate By Models Center": "绕模型中心旋转",
		"Exit": "退出",
		"app is not verified":"程序未校验",
		"The file is damaged": "文件已损坏",
		"current models contain protected model! can not do this operation!":"当前模型中包含受保护的模型！不能进行此操作！",
		"UnKnown ERROR!Please Contact TierTime!":"未知错误！请联系我们",
		"Copy Number: ": "复制个数",
		"Copy Model": "复制模型",
		"1 model": "1 个模型",
		"2 model": "2 个模型",
		"3 model": "3 个模型",
		"4 model": "4 个模型",
		"5 model": "5 个模型",
		"6 model": "6 个模型",
		"7 model": "7 个模型",
		"8 model": "8 个模型",
		"custom": "自定义",
		"Voxelization": "体素化",
		"Edit":"编辑",
		"Voxel Size":"体素大小"
	},
	"image_front": {
		"_Model_Height": "模型高度",
		"_Base_Height": "基底高度",
		"_Style": "风格",
		"_Model_Size": "模型大小",
		"_Unit": "单位(mm)",
		"_Pen_Size": "画笔大小",
		"_Pen_Color": "画笔颜色",
		"_Pen_Type": "画笔种类",
		"_Erase_Size": "橡皮擦大小",
		"_Font": "字体",
		"_Font_Size": "文字大小",
		"_Font_Color": "文字颜色",
		"_Constrain": "等比例",
		"_Tools": "工具",
		"_Setting": "设置",
		"_Previous": "上一步",
		"_Apply": "应用",
		"_Go_back": "返回",
		"_Pen": "画笔",
		"_Rubber": "橡皮",
		"_Text": "文字",
		"_Cut": "裁剪",
		"_Toggle_color": "黑白转换",
		"_choose_model_base": "选择基底",
		"_image_image": "图片",
		"_image_loop": "灯罩",
		"_image_pic": "相框",
		"_image_relative": "相对"
	},
     "image": { }
}
