var english={
    "version": "1.2",
    "date": "2016-9-12",
    "_front": {
        "name": "en",
        "systemError": "System Error",
        "tt_systemunlink": "No UP printers found",
        "tt_systemerror": "Printer not Initialized",
        "tt_prepared": "Printer Ready",
        "tt_runing": "Print Job in Progress",
        "tt_pause": "Print Job Paused",
        "tt_nozzleerror": "Nozzle Error",
        "tt_motionerror": "Motion System Error",
        "tt_finished": "Print Job Finished",
        "tt_userstop": "Print Job Stopped",
        "tt_temphigh": "Nozzle Too Hot",
        "tt_templow": "Nozzle Too Cool",
        "tt_workroomhigh": "Platform Too Hot",
        "tt_reverse_1": "tt_reverse_1",
        "tt_reverse_2": "tt_reverse_2",
        "tt_reverse_3": "tt_reverse_3",
        "tt_reverse_4": "tt_reverse_4",
        "tt_systempoweron": "System Powered ON",
        "tt_sdcarderror": "SD Card Error",
        "tt_sdwberror": "SD Card Write Error",
        "tt_sdrberror": "SD Card Read Error",
        "tt_savetosd": "Save to SD Card",
        "tt_jogcmderror": "Joggle Error",
        "tt_copyrightzero": "Copyright Limitation",
        "tt_printtimelimit": "Print Number Limitation",
        "tt_commerror": "Communication Error",
        "printerName": "Printer Name",
        "nozzleTemperature": "Nozzle(℃)",
        "flatTemperature": "Platform(℃)",
        "m_nMaterial": "Material",
        "printerTxt": "Printer Name",
        "m_dNozzleHeight": "Nozzle Height",
        "btn_aboutUs": "About Us",
        "btn_myCounts": "Account",
        "btn_up": "UP",
        "btn_libiray": "Library",
        "btn_help": "Help",
        "dialogTitle_add": "Add",
        "dialogAdd_photo": "Add Picture",
        "dialogAdd_stl": "Add Model",
        "dialogTitle_layer": "Setting",
        "dialogTitle_Z_resolution": "Layer Thickness",
        "dialogTitle_part": "Part",
        "dialogTitle_Surface": "Surface",
        "dialogTitle_Surface_SupportAngle": "Angle",
        "dialogTitle_Support": "Support",
        "dialogTitle_Dense": "Dense",
        "dialogTitle_Support_Angle": "Angle",
        "dialogTitle_Support_Area": "Area",
        "dialogTitle_Support_Space": "Space",
        "dialogTitle_Stable_Support": "Stable Support",
        "dialogTitle_Fill": "Infill",
        "dialogTitle_fill_shell": "Shell",
        "dialogTitle_fill_surface": "Surface",
        "dialogTitle_fill_solid": "Solid",
        "dialogTitle_fill_Loose": "Loose",
        "dialotTitle_fill_Hollow": "Hollow",
        "dialogTitle_fill_BigHole": "Big Hole",
        "ResettoDefault": "Default",
        "save": "Save",
        "unsave": "Cancel",
        "dialogTitle_Maintain": "Maintenance",
        "dialogTitle_Maintenance": "Maintenance",
        "dialogTitle_Extrude": "Extrude",
        "dialogTitle_Evacuate": "Withdraw",
        "Stop": "Stop",
        "Weight": "Weight",
        "dialogTitle_PrinterSetting": "Printer Setting",
        "dialogTitle_printerName": "Printers",
        "dialogTitle_UnsolidModel": "Unsolid Model",
        "dialogTitle_NoRaft": "No Raft",
        "dialogTitle_heat": "Keep Heating After Print Job Finished",
        "dialogTitle_Quality": "Quality",
        "option": "Option",
        "reprint": "Reprint",
        "preview": "Preview",
        "dialogTitle_Calibrate": "Calibration",
        "platMainH3": "Platform Calibration",
        "printBtn": "Print",
        "exit": "Exit",
        "save3DModeling_txt": "Saving",
        "ImgTo3D_txt": "Conversing",
        "Time_left": "Time Left",
        "initialPrinter": "Printer Initializing",
        "logIn": "Login",
        "preference": "Preference",
        "no_Support": "No Support",
        "thinWall": "Thin Wall",
        "others": "Others",
        "autoPlace": "Auto Place",
        "noRecentFile": "No Recent File",
        "autoUpdateTxt": "Remind me of the new version",
        "apError": "Failed to locate WiFi",
        "auto": "Auto",
        "manual": "Manual",
        "platAutoIng": "Platform Auto Calibration in Progress...",
        "nozzleAutoIng": "Nozzle Auto Calibration in Progress...",
        "autoError": "Sensor not connected",
        "errorTxt": "Error",
        "successTxt": "Success",
        "connectTxt": "Connecting...",
        "setSuccessTxt": "Set Succeeded",
        "setErrorTxt": "Set Failed",
        "convert": "Converting",
        "nozzleHeating": "Wait a moment...",
        "math": "Slicing",
        "transfer": "Sending",
        "normal": "Normal",
        "fine": "Fine",
        "fast": "Fast",
        "timeH": "h",
        "timeM": "m",
        "timeS": "s",
        "connectSuccessTxt": "Connected",
        "connectErrorTxt": "Failed to connect",
        "languageTxt": "Language",
        "PrinterTxt": "Printer",
        "wifiTxt": "WiFi",
        "UpdateTxt": "Upgrade",
        "currentTxt": "Current",
        "newTxt": "Latest",
        "axisTxt": "No Axis Chosen",
        "yes": "Confirm",
        "no": "Cancel",
        "printerInitTips": "Initialize Printer?",
        "printerStopTips": "Stop the Current Print Job?",
        "manualUpdate": "Update",
        "justTxt1": "Just Enter",
        "justTxt2": "Number",
        "justTxt3": "",
        "nameError": "Printer Name Cannot Be Empty.",
        "custom": "Customized",
        "txtObject": "Object",
        "share": "Share",
        "verTips": "Your System is UP-to-date",
        "nozzleCurrentHeight": "Current Nozzle Height",
        "nozzleSetHeight": "Nozzle Height",
        "reset": "Reset",
        "compensation": "Leveling",
        "pausePrintError": "Failed to Pause Print Job",
        "resumePrintError": "Failed to Resume Print Job",
        "nozzleTo": "Move",
        "set": "Set",
        "detectNozzle": "Nozzle Detect",
        "autoLevel": "Auto Level",
        "saveSetNozzleHeight": "Set Nozzle Height as ",
        "intNumberTips": "Range is from",
        "previewStopTips": "Confirm to Stop?",
        "privacy": "Please review Tiertime Privacy Policy to know about the details of data collection of UP Studio.<br />You can choose to turn on or off the data collection function base on your preference.",
        "privacyTxt": "Privacy Policy",
        "privacyBtn": "Details",
        "tooltip_backIndexPages": "Home",
        "tooltip_add": " Import Model or Image",
        "tooltip_btnPrint": "Print",
        "tooltip_stopPrint": "Stop Printing",
        "tooltip_pausePrint": "Pause",
        "tooltip_resumePrint": "Resume",
        "tooltip_stopPreview": "Stop Preview",
        "tooltip_initPrinter": "Initialize Printer",
        "tooltip_btnPlat": "Calibrate",
        "tooltip_btnMar": "Maintenance",
        "tooltip_circle_move": "Move",
        "tooltip_circle_zoom": "Scale",
        "tooltip_circle_class": "More",
        "tooltip_circle_view": "View",
        "tooltip_circle_back": "Undo",
        "tooltip_circle_fit": "Auto Place",
        "tooltip_circle_rotate": "Rotate",
        "tooltip_circle_mirror": "Mirror",
        "tooltip_circle_save": "Save Model",
        "tooltip_circle_reset": "Reset to Default",
        "tooltip_circle_fixded": "Fix Errors",
        "tooltip_circle_merge": "Merge",
        "tooltip_circle_del": "Delete",
        "tooltip_view_top": "Top View",
        "tooltip_view_bottom": "Bottom View",
        "tooltip_view_back": "Back View",
        "tooltip_view_free": "Free View",
        "tooltip_view_right": "Right View",
        "tooltip_view_front": "Front View",
        "tooltip_view_left": "Left View",
        "tooltip_top_my": "My Account",
        "tooltip_top_setting": "Setting",
        "tooltip_top_share": "Share",
        "tooltip_top_skin": "Skin",
        "turbo": "Turbo",
        "EnterPwd": "Please Enter Password",
        "statusError": "Status Error",
        "EmailWrong": "Email or Username Error",
        "PasswordErr": "Please Enter Password with 6-32 Characters",
        "CodeErr": "Validation Code Error",
        "LoginFail": "Login Failed",
        "Email": "Email",
        "password": "Password",
        "code": " Validation Code",
        "reprint_location": "Slot",
        "reprint_number": "NO.",
        "model_name": "Model Name",
        "reprint_time": "Time",
        "reprint_date": "Date",
        "reprint_select": "Choose",
        "pre_heat": "Preheat",
        "custom_material": "Customized",
        "custom_material_title": "Customized Material",
        "material": "Material",
        "material_name": "Name",
        "nozzle_temp": "Nozzle(℃)",
        "baseboard_temp": "Platform(℃)",
        "operation": "Process",
        "edit": "Edit",
        "delete": "Delete",
        "add_material": "Add",
        "cancel": "Cancel",
        "materials_repeat": "Error:Material Name Duplicated",
        "materials_7": "Only 7 Materials Allowed",
        "cuatom_material_title": "Customized Material",
        "user_login": "Login",
        "user_name_hint": "Username or Email",
        "password_hint": "Password",
        "sign_in": "Sign In",
        "sign_up": "Sign Up",
        "ifremember": "Remember Me",
        "forget_password": "Forgot Password?",
        "username": "Username (3-20 Characters Starting with a Letter)",
        "email": "Email (Enter an Email Address)",
        "sign_up_password":"Password (6-32 Characters)",
        "ConfirmPassword": "Confirm Password (Input Password Again)",
        "username_error": "Invalid Username",
        "email_error": "Invalid Email Address",
        "password_error": "Invalid Password",
        "confirm_error": "Passwords Do Not Match",
        "registration_statement": "Registration means you agree with",
        "agreement": "Tiertime End User Agreement",
        "login_info": "Printer Management",
        "online_device": "My Printers",
        "my_device": "My Device",
        "net_error": "Network Problems and Please Try Later",
        "device_sn": "Serial Number",
        "activate_status": "Activation Status",
        "bind_status": "Binding Status",
        "activate": "Activate",
        "activated": "Activated",
        "bind": "Bind",
        "binded": "Bound",
        "unbind": "Unbind",
        "unbind_success":"Unbind Successfully",
        "unbind_fail":"Failed to Unbind",
        "bind_success":"Binding Successfully",
        "fail":"Failed",
        "activate_success":"Activation Succeeded",
        "user_unexist":"User does not Existed",
        "reset_fail":"Failed to Reset Password",
        "login_fail":"Failed to Login",
        "reset_email_success":"An email to reset your password has been sent to your email address",
        "no data cache":"No Data in Cache",
        "login timeout":"Login Timeout",
        "can not find sn device":"Cannot locate the device with the Serial Number",
        "Save failed":"Failed to Save",
        "password_wrong":"Password is Incorrect",
        "unactivate":"User Account has not been Activated",
        "un_signup":"Username is not registered",
        "Parameter is not complete":"Incomplete Parameters",
        "Parameters calibration error":"Parameters Check Error",
        "UserExists":"Username has been Used",
        "datasavefail":"Failed to Save Data",
        "signup_success":"Registration Successful",
        "congratulation":"Congratulations",
        "success_text":"Registration is successful. An activation code has been sent to your email account. Please click the link in your email to activate your account.",
        "change_pic":"Change image",
        "toggle_black_white":"Toggle color",
        "translate_to_3d_model":"Transform to 3D model",
        "back":"Return Back",
        "sure_to_translate":"Confirm to Transform？",
        "only_num":"Please Enter Numbers",
        "only_num_letter":"Only Numbers and Characters Allowed",
        "Select save slot":"Select Saved Slot",
        "Fill in the incomplete":"Fields can not be Empty",
        "UserNameExisted":"Username has been used.",
        "EmailExisted":"Email account has been used.",
        "Login_out":"Sign out",
        "please_login":"Please sign in your account",
        "software_skin":"Skin Color",
        "model_color":"Model Color",
        "now_color":"Current",
        "base_color":"Basic",
        "current_language":"Current Language",
        "baseHeight":"Base Height",
        "modelHeight":"Model Height",
        "sure": "Confirm",
        "selectPlatType": "Please Choose Plate Type",
        "perforated plate": "Perforated",
        "flex": "Flex",
        "enterLoginInfo": "Please enter your username and password",
        "enterUsername": "Please enter user name",
        "enterPassword": "Please enter your password",
        "restTitle":"Dormancy",
        "materialHeat":"Preheat",
        "platManSet":"Manual",
          "platManSetHeight":"Set nozzle height is:",
        "dialog_manu":"Demo Op.",
        "dialog_manu_end":"Demo Op. Over",
        "compensation":"Compensation",
	"modeInfoTitle":"Model Properties",
        "modeInfomMark":"Basic",
        "Filepath": "File Path: ",
        "Size": "Size(mm): ",
        "MinSize": "Min-Size(mm): ",
        "MaxSize": "Max-Size(mm): ",
        "Vertex":"Vertex Number: ",
        "Facet": "Facet Number: ",
        "Volume": "Volume(mm³): ",
        "area":"Surface area(mm²)："
    },
    "print": {
        "PrinterStatus-1": "Printer not Connected",
        "PrinterStatus0": "Printer not Initialized",
        "PrinterStatus1": "Printer Ready",
        "PrinterStatus2": "Print Job in Progress",
        "PrinterStatus3": "Print Job Paused",
        "PrinterStatus4": "Nozzle Error",
        "PrinterStatus5": "Motion System Error",
        "PrinterStatus6": "Print Job Finished",
        "PrinterStatus7": "Print Job Stopped",
        "PrinterStatus8": "Nozzle Too Hot",
        "PrinterStatus9": "Nozzle Too Cool",
        "PrinterStatus10": "Platform Too Hot",
        "PrinterStatus11": "tt_reserved_1",
        "PrinterStatus12": "tt_reserved_2",
        "PrinterStatus13": "tt_reserved_3",
        "PrinterStatus14": "tt_reserved_4",
        "PrinterStatus15": "System Powered ON",
        "PrinterStatus16": "SD Card Error",
        "PrinterStatus17": "SD Card Write Error",
        "PrinterStatus18": "SD Card Read Error",
        "PrinterStatus19": "Save to SD Card",
        "PrinterStatus20": "Joggle Error",
        "PrinterStatus21": "Copyright Limitation",
        "PrinterStatus22": "Print Number Limitation",
        "PrinterStatus23": "Communication Error",
        "ERROR": "ERROR",
        "ERROR: Task cannot be performed during printing": "ERROR: Task cannot be performed during on going print jobs.",
        "ERROR: Incorrect material": "ERROR: Incorrect Material.",
        "ERROR: Printer status error": "ERROR: Printer Status Error.",
        "ERROR: Slicing error": "ERROR: Slicing Error.",
        "ERROR: Printer connection error": "ERROR: Printer Connection Error.",
        "ERROR: Data transfer failure": "ERROR: Data Transfer Failure.",
        "ERROR: Printer is busy,please stop and try again": "ERROR: Printer is busy. Please wait until it stops and then try again.",
        "ERROR: Printer material shortage,still continue?": "ERROR: Printer is short of material, still continue?",
        "ERROR: Printer support material shortage,still continue?": "ERROR: Printer is short of support material, still continue?",
        "ERROR: Nozzleheight set error</br>Correct range:": "ERROR: Failed to set Nozzle height</br>Correct range:",
        "Repeat last print?": "Repeat Last Print?",
        "ERROR: Other error ": "ERROR: Other Errors.",
        "Language test": "Language Test",
        "Are you sure to stop the print job?": "Confirm to stop the current print job?",
        "Found a new version": "A new version of software has been found",
        ",download it immediately?": ",download it immediately?",
        "[YES]: Update immediately": "[YES]: Update Immediately",
        "[NO]: Remind me later": "[NO]: Remind Me Later",
        "[CANCEL]: Switch off update reminder": "[CANCEL]: Switch Off Update Reminder",
        "Note: Download will be running in the background, after the completion of the notice": "Note: Download will be running in the background. You will be notified after the completion .",
        "Update": "Update",
        "No new version": "No New Version.",
        "ERROR: The model is opening, please try again later": "ERROR: The model is being loaded. Please try again later.",
        "ERROR: Temperature is too high": "ERROR: Temperature is too high.",
        "ERROR: Sensor not connected": "ERROR: Sensor is not connected.",
        "ERROR: Calibration failure": "ERROR: Calibration failed.",
        "ERROR: Printer is busy": "ERROR: Printer is busy.",
        "Success，Please reset nozzle height before printing": "Success: Please reset the nozzle height before printing.",
        "ERROR: Printer error": "ERROR: Printer Error.",
        "Print: ": "Print: ",
        "Material: ": "Material: ",
        "g": "g",
        "H": "H",
        "M": "M",
        "S": "S",
        "ERROR: Templete directory get error": "ERROR: Failed to locate the temporary directory.",
        "ERROR: Create dir error": "ERROR: Failed to create directory",
        "ERROR: Copy UpdateFile Error_APP": "ERROR: Failed to Copy Update File_APP",
        "ERROR: Copy UpdateFile Error_DLL": "ERROR: Failed to Copy Update File_DLL",
        "ERROR: Nozzleheight set error": "ERROR: Failed to Set Nozzle Height",
        "ERROR:Model does not exist": "ERROR: Model not found",
        "Activation": "Activation",
        "Please activate the printer in time to use the full printer functions": "Please activate the printer to use the full power of UP Printers",
        "Activation state error, need to return to the factory": "Failed to activate the printer. Please contact the manufacturer.",
        "OK": "OK",
        "CANCEL": "CANCEL",
        "YES": "YES",
        "NO": "NO",
        "ABORT": "ABORT",
        "RETRY": "RETRY",
        "IGNORE": "IGNORE",
        "Save successful": "Save succeeded.",
        "Save failed": "Save failed.",
        "Downloading, please wait": "Download in progress. Please wait.",
        ",upgrade now?": ",upgrade now?",
        "Level data save error": "Failed to Save Leveling Data.",
        "ERROR: Printer no response": "ERROR: Printer not Responding.",
        "ERROR: Printer password error": "ERROR: Incorrect Printer Password.",
        "ERROR: Printer connected by other clients": "ERROR: Printer is being used by other users.",
        "ERROR: Printer none certification": "ERROR: Printer is not certified.",
        "Connection OK": "Connection OK.",
        "Connection Error": "Connection Error.",
        "Activation is successful, please restart the printer": "Activation succeeded. Please restart the printer.",
        "Can not Save more than 4 millon facets model": "Cannot save models with more than 4 million facets.",
        "No Model Selected":"No model is selected",
        "warning!":"Warning!",
        "    Delete Selected Model?":"    Delete Selected Models?",
        "    Delete All Models?":"    Delete all of Models?",
        "Please close the front door": "Please Close the Front Door.",
        "Model is too large! Can not Load": "Model is too large. Loading Failed",
		"Loading Failed":"Loading Failed!",
        "Print job stopped at ": "Print Job Stopped at layer No.",
        "th layer, resume the print?": ". Resume the Print Job?",
        "ERROR: Can't resume the broken print job": "ERROR: Cannot Resume the Stopped Print Job.",
        "ERROR: Data transfer failed, try again?": "ERROR: Data Transfer Failed. Try again?",
        "OpenGL Version Too Low! Check your Graphic Drivers!": "Please upgrade OpenGL, and check your graphic card drivers!",
        "ERROR: Printer SN Error": "ERROR: Printer Serial Number Error",
        "ERROR: Unknow error": "ERROR: Unknown Error",
        "ERROR: Invalide activekey": "ERROR: Invalid Activation Key",
        "ERROR: No factory actived": "ERROR: Not Factory Activated",
        "ERROR: Active error,wrong key": "ERROR: Activation Error. Invalid Key",
        "ERROR: The server returns the activation code to parse the JSON failed": "ERROR: Activation data returned from server failed.",
        "ERROR: The server failed to return the activation code": "ERROR: The server failed to return the activation code",
        "ERROR: Failed to get the check code from the printer": "ERROR: Failed to get the checksum data from the printer",
        "ERROR: The current state of activation is not factory activation": "ERROR: The current activation status is not factory activation",
        "ERROR: Failed to obtain an active state": "ERROR: Failed to obtain the activation status.",
        "ERROR: Model out of print bound": "ERROR: Model out of Bound of Print Area",
        "ERROR: Calibration Failure": "ERROR: Calibration Failed",
        "ERROR: Server connection failed": "ERROR: Server Connection Failed",
        "ERROR: Verification Failed,Please download activation package": "ERROR: Verification Failed. Please Download Activation Package",
        "[YES] Perf Board\r\n[NO] Flex Board": "[YES] Perf Board\r\n[NO] Flex Board",
        "Please Select The Type Of Plat": "Please Select the Type Of Plat",
        "ERROR: Temperature is low": "ERROR: Temperature is Low",
        "Do you want to keep current model?": "Do you want to keep current model?"
    },
    "graphic": {
        "Filepath: ": "File Path: ",
        "Size(mm): ": "Size(mm): ",
        "Min-Size(mm): ": "Min-Size(mm): ",
        "Max-Size(mm): ": "Max-Size(mm): ",
        "Vertex Number: ": "Vertex Number: ",
        "Facet Number: ": "Facet Number: ",
	    "Volume: ": "Volume: ",
        "Copying...":"Copying Models ...",
        "Saveing...":"Saving Models ...",
        "has scaled from inch unit to mm unit!":"has scaled from inch unit to mm unit!",
        "Property":"Property",
		"Copy":"Copy",
		"1 model":"1 Copy",
		"2 model":"2 Copys",
		"5 model":"5 Copys",
		"Delete":"Delete",
		"Delete All":"Delete All",
		"Select All":"Select All",
		"UnSelect All":"Unselect All",
		"Initialize View":"Initialize View",
		"Rotate By Models Center":"Rotate around the Center of Models",
		"Exit":"Exit"
    },
    "image_front": {
        "_Model_Height":"Model Height",
        "_Base_Height":"Base Height",
        "_Style":"Style",
        "_Model_Size":"Model Size",
        "_Unit":"Unit(mm)",
        "_Pen_Size":"Pen Size",
        "_Pen_Color":"Pen Color",
        "_Pen_Type":"Pen Type",
        "_Erase_Size":"Erase Size",
        "_Font":"Font",
        "_Font_Size":"Font Size",
        "_Font_Color":"Font Color",
        "_Constrain":"Constrain",
        "_Tools":"Tools",
        "_Setting":"Setting",
        "_Previous":"Previous",
        "_Apply":"Apply"
    },
     "image": { }
}

var chinese ={
    "version": "2.0",
    "date": "2016-9-12",
    "_front": {
        "name": "zh",
        "systemError": "系统错误",
        "tt_systemunlink": "打印机未连接",
        "tt_systemerror": "未初始化",
        "tt_prepared": "打印机准备就绪",
        "tt_runing": "打印中",
        "tt_pause": "暂停打印",
        "tt_nozzleerror": "喷嘴错误",
        "tt_motionerror": "运动系统错误",
        "tt_finished": "打印完成",
        "tt_userstop": "打印被停止",
        "tt_temphigh": "喷嘴温度过高",
        "tt_templow": "喷嘴温度过低",
        "tt_workroomhigh": "平台温度过高",
        "tt_reverse_1": "tt_reverse_1",
        "tt_reverse_2": "tt_reverse_2",
        "tt_reverse_3": "tt_reverse_3",
        "tt_reverse_4": "tt_reverse_4",
        "tt_systempoweron": "系统上电",
        "tt_sdcarderror": "SD卡错误",
        "tt_sdwberror": "SD卡写入错误",
        "tt_sdrberror": "SD卡读取错误",
        "tt_savetosd": "保存打印数据至SD卡",
        "tt_jogcmderror": "移动指令错误",
        "tt_copyrightzero": "版权限制",
        "tt_printtimelimit": "打印次数限制",
        "tt_commerror": "通讯错误",
        "printerName": "打印机名称",
        "nozzleTemperature": "喷嘴(℃)",
        "flatTemperature": "平台(℃)",
        "m_nMaterial": "材料",
        "printerTxt": "打印机名称",
        "m_dNozzleHeight": "喷嘴高度",
        "btn_aboutUs": "关于我们",
        "btn_myCounts": "我的账户",
        "btn_up": "UP",
        "btn_libiray": "资料库",
        "btn_help": "帮助",
        "dialogTitle_add": "添加",
        "dialogAdd_photo": "添加图像",
        "dialogAdd_stl": "添加模型",
        "dialogTitle_layer": "设置",
        "dialogTitle_Z_resolution": "层片厚度",
        "dialogTitle_part": "密闭",
        "dialogTitle_Surface": "密闭层数",
        "dialogTitle_Surface_SupportAngle": "密闭角度",
        "dialogTitle_Support": "支撑",
        "dialogTitle_Dense": "支撑层数",
        "dialogTitle_Support_Angle": "支撑角度",
        "dialogTitle_Support_Area": "支撑面积",
        "dialogTitle_Support_Space": "支撑间隔",
        "dialogTitle_Stable_Support": "稳固支持",
        "dialogTitle_Fill": "填充方式",
        "dialogTitle_fill_shell": "shell",
        "dialogTitle_fill_surface": "surface",
        "dialogTitle_fill_solid": "solid",
        "dialogTitle_fill_Loose": "loose",
        "dialotTitle_fill_Hollow": "Hollow",
        "dialogTitle_fill_BigHole": "Big Hole",
        "ResettoDefault": "设置默认",
        "save": "保存",
        "unsave": "取消",
        "dialogTitle_Maintain": "维护界面",
        "dialogTitle_Maintenance": "维护",
        "dialogTitle_Extrude": "挤出",
        "dialogTitle_Evacuate": "撤回",
        "Stop": "停止",
        "Weight": "重量",
        "dialogTitle_PrinterSetting": "打印设置",
        "dialogTitle_printerName": "打印机",
        "dialogTitle_UnsolidModel": "非实体模型",
        "dialogTitle_NoRaft": "无底座",
        "dialogTitle_heat": "打印完成平台持续加热",
        "dialogTitle_Quality": "质量",
        "option": "选项",
        "reprint": "重复打印",
        "preview": "打印预览",
        "dialogTitle_Calibrate": "平台校准",
        "platMainH3": "平台点位校准",
        "saveImgTo3D_txt": "图像转换中",
        "save3DModeling_txt": "保存中",
        "printBtn": "打印",
        "exit": "退出",
        "ImgTo3D_txt": "转换中",
        "Time_left": "剩余",
        "initialPrinter": "初始化进行中",
        "logIn": "登录",
        "preference": "高级",
        "no_Support": "无支撑",
        "thinWall": "薄壁",
        "others": "其他",
        "autoPlace": "自动摆放",
        "noRecentFile": "没有最近打开",
        "autoUpdateTxt": "有版本更新时请提醒我",
        "apError": "无线网络查找错误",
        "auto": "自动",
        "manual": "手动",
        "platAutoIng": "平台自动调整中,请稍后...",
        "nozzleAutoIng": "喷嘴自动调整中,请稍后...",
        "autoError": "传感器未连接",
        "errorTxt": "错误",
        "connectTxt": "正在连接，请稍后...",
        "successTxt": "成功",
        "setSuccessTxt": "设置成功",
        "setErrorTxt": "设置失败",
        "convert": "转换中",
        "nozzleHeating": "稍等片刻...",
        "math": "计算中",
        "transfer": "传输中",
        "normal": "默认",
        "fine": "较好",
        "fast": "较快",
        "timeH": "小时",
        "timeM": "分钟",
        "timeS": "秒",
        "connectSuccessTxt": "连接成功",
        "connectErrorTxt": "连接失败",
        "languageTxt": "语言",
        "PrinterTxt": "打印机",
        "wifiTxt": "无线网络",
        "UpdateTxt": "软件升级",
        "currentTxt": "当前版本",
        "newTxt": "最新版本",
        "axisTxt": "未选择轴方向",
        "yes": "确认",
        "no": "取消",
        "printerInitTips": "是否初始化打印机？",
        "printerStopTips": "是否停止打印？",
        "manualUpdate": "升级",
        "justTxt1": "只能输入",
        "justTxt2": "的数噢",
        "justTxt3": "之间的数字哦~",
        "nameError": "打印机名字不能为空~",
        "custom": "自定义",
        "txtObject": "模型",
        "share": "分享到",
        "verTips": "当前版本已是最新",
        "nozzleCurrentHeight": "喷嘴当前高度",
        "nozzleSetHeight": "喷嘴高度",
        "reset": "重置",
        "compensation": "补偿",
        "pausePrintError": "暂停失败",
        "resumePrintError": "恢复打印失败",
        "nozzleTo": "移动",
        "set": "设置",
        "detectNozzle": "自动对高",
        "autoLevel": "自动补偿",
        "saveSetNozzleHeight": "保存喷嘴高度为",
        "intNumberTips": "范围的整数",
        "previewStopTips": "是否停止？",
        "privacy": "请查看 UPStudio 的隐私声明以了解有关如何使用发送到 UPStudio 的数据的详细信息 , 您可以选择是否对应用程序启用数据收集功能.",
        "privacyTxt": "隐私声明",
        "privacyBtn": "查看详情",
        "tooltip_backIndexPages": "首页",
        "tooltip_add": "添加模型或图片",
        "tooltip_btnPrint": "打印",
        "tooltip_stopPrint": "停止打印",
        "tooltip_pausePrint": "暂停打印",
        "tooltip_resumePrint": "恢复打印",
        "tooltip_stopPreview": "停止预览",
        "tooltip_initPrinter": "初始化打印机",
        "tooltip_btnPlat": "校准",
        "tooltip_btnMar": "维护",
        "tooltip_circle_move": "移动",
        "tooltip_circle_zoom": "缩放",
        "tooltip_circle_class": "类别",
        "tooltip_circle_view": "视图",
        "tooltip_circle_back": "回退",
        "tooltip_circle_fit": "自动摆放",
        "tooltip_circle_rotate": "旋转",
        "tooltip_circle_mirror": "镜像",
        "tooltip_circle_save": "保存模型",
        "tooltip_circle_reset": "重置",
        "tooltip_circle_fixded": "修复",
        "tooltip_circle_merge": "合并",
        "tooltip_circle_del": "删除",
        "tooltip_view_top": "顶视图",
        "tooltip_view_bottom": "底视图",
        "tooltip_view_back": "后视图",
        "tooltip_view_free": "自由视图",
        "tooltip_view_right": "右视图",
        "tooltip_view_front": "前视图",
        "tooltip_view_left": "左视图",
        "tooltip_top_my": "账户",
        "tooltip_top_setting": "设置",
        "tooltip_top_share": "分享",
        "tooltip_top_skin": "皮肤",
        "turbo": "极快",
        "statusError": "打印机未知错误",
        "EnterPwd": "请输入密码",
        "EmailWrong": "邮箱或用户名错误",
        "PasswordErr": "请输入6-32位密码",
        "CodeErr": "验证码错误",
        "LoginFail": "登陆失败",
        "Email": "邮箱",
        "password": "密码",
        "code": "验证码",
        "reprint_location": "槽位",
        "reprint_number": "序列号",
        "model_name": "模型名称",
        "reprint_time": "时间",
        "reprint_date": "日期",
        "reprint_select": "选择",
        "pre_heat": "预热",
        "custom_material": "自定义",
        "custom_material_title": "自定义材料",
        "material": "材料",
        "material_name": "名字",
        "nozzle_temp": "喷头(℃)",
        "baseboard_temp": "底板(℃)",
        "operation": "操作",
        "edit": "编辑",
        "delete": "删除",
        "add_material": "添加",
        "cancel": "取消",
        "materials_repeat": "材料名重复",
        "materials_7": "自定义材料最多7个",
        "cuatom_material_title": "自定义材料",
        "user_login": "用户登录",
        "user_name_hint": "邮箱/用户名",
        "password_hint": "密码",
        "sign_in": "登录",
        "sign_up": "注册",
        "ifremember": "记住密码",
        "forget_password": "忘记密码?",
        "username": "用户名（3-20个字符，以字母开头）",
        "email": "邮箱（请输入您的邮箱）",
        "sign_up_password": "密码（密码为6-32位字符）",
        "ConfirmPassword": "确认密码（再次输入密码）",
        "username_error": "用户名输入不合法",
        "email_error": "邮箱输入不合法",
        "password_error": "密码输入不合法",
        "confirm_error": "两次密码输入不同",
        "registration_statement": "注册表示您同意",
        "agreement": "《太尔时代用户协议》",
        "login_info": "打印机管理",
        "online_device": "我的打印机",
        "my_device": "我的设备列表",
        "net_error": "网络出问题了，请稍后再试",
        "device_sn": "设备sn号",
        "activate_status": "激活状态",
        "bind_status": "绑定状态",
        "activate": "激活",
        "activated": "已激活",
        "activate_fail": "激活失败",
        "bind": "绑定",
        "binded": "已绑定",
        "unbind": "解除绑定",
        "unbind_success": "解绑成功",
        "unbind_fail": "解绑失败，设备尚未绑定",
        "bind_success": "绑定成功",
        "fail": "失败",
        "activate_success": "激活成功",
        "user_unexist": "用户不存在",
        "reset_fail": "密码重置失败",
        "login_fail": "登录失败",
        "reset_email_success": "重置密码邮件发送成功",
        "no data cache": "缓存中无数据",
        "login timeout": "登录超时",
        "can not find sn device": "未找到sn对应的设备",
        "Save failed": "保存失败",
        "password_wrong": "密码错误",
        "unactivate": "用户未激活",
        "un_signup": "购买商品未注册",
        "Parameter is not complete": "参数不完整",
        "Parameters calibration error": "参数校验错误",
        "UserExists": "用户已存在",
        "datasavefail": "数据保存失败",
        "signup_success": "注册成功",
        "congratulation": "恭喜",
        "success_text": "注册成功，激活码已发送到您的邮箱，请点击激活",
        "change_pic": "更换图片",
        "toggle_black_white": "黑白转换",
        "translate_to_3d_model": "转成3d模型",
        "back": "返回",
        "sure_to_translate": "确定转换？",
        "only_num": "只能输入数字",
        "only_num_letter": "只能输入数字和英文字符",
        "Select save slot": "选择保存槽位",
        "Fill in the incomplete": "填写不完整",
        "UserNameExisted": "用户名已存在",
        "EmailExisted": "邮箱已被注册",
        "Login_out": "退出",
        "please_login": "请登录您的账户",
        "software_skin": "界面颜色",
        "model_color": "模型颜色",
        "now_color": "当前颜色",
        "base_color": "基础色",
        "current_language": "当前语言",
        "baseHeight": "基底高度",
        "modelHeight": "模型高度",
        "sure": "确定",
        "selectPlatType": "请选择底板类型",
        "perforated plate": "多孔板",
        "flex": "Flex板",
        "enterLoginInfo": "请输入用户名和密码",
        "enterUsername": "请输入用户名",
        "enterPassword": "请输入密码",
        "restTitle":"休眠",
        "materialHeat":"平台加热",
        "platManSet":"手动校准",
        "platManSetHeight":"设置喷嘴高度为:",
        "dialog_manu":"演示操作",
        "dialog_manu_end":"演示结束",
        "compensation":"补偿",
        "modeInfoTitle":"模型属性",
        "modeInfomMark":"基本信息",
        "Filepath": "文件路径: ",
        "Size": "模型尺寸(mm): ",
        "MinSize": "最小位置(mm): ",
        "MaxSize": "最大位置(mm): ",
        "Vertex":"顶点数目: ",
        "Facet": "面片数目: ",
        "Volume": "体积(mm³): ",
        "area":"表面积(mm²)："
    },
    "print": {
        "PrinterStatus-1": "打印机未连接",
        "PrinterStatus0": "未初始化",
        "PrinterStatus1": "打印机准备就绪",
        "PrinterStatus2": "打印中",
        "PrinterStatus3": "暂停打印",
        "PrinterStatus4": "喷嘴错误",
        "PrinterStatus5": "运动系统错误",
        "PrinterStatus6": "打印完成",
        "PrinterStatus7": "打印被停止",
        "PrinterStatus8": "喷嘴温度过高",
        "PrinterStatus9": "喷嘴温度过低",
        "PrinterStatus10": "平台温度过高",
        "PrinterStatus11": "tt_reverse_1",
        "PrinterStatus12": "tt_reverse_2",
        "PrinterStatus13": "tt_reverse_3",
        "PrinterStatus14": "tt_reverse_4",
        "PrinterStatus15": "系统上电",
        "PrinterStatus16": "SD卡错误",
        "PrinterStatus17": "SD卡写入错误",
        "PrinterStatus18": "SD卡读取错误",
        "PrinterStatus19": "保存打印数据至SD卡",
        "PrinterStatus20": "移动指令错误",
        "PrinterStatus21": "版权限制",
        "PrinterStatus22": "打印次数限制",
        "PrinterStatus23": "通讯错误",
        "ERROR": "发生错误",
        "ERROR: Task cannot be performed during printing": "错误：打印机运行中，不能进行此操作",
        "ERROR: Incorrect material": "错误：打印机材料设置错误",
        "ERROR: Printer status error": "错误：打印机状态错误",
        "ERROR: Slicing error": "错误：分层错误",
        "ERROR: Printer connection error": "错误：打印机连接错误",
        "ERROR: Data transfer failure": "错误：传输打印数据失败",
        "ERROR: Printer is busy,please stop and try again": "错误：系统正忙，请停止后再试",
        "ERROR: Printer material shortage,still continue?": "错误：打印材料不足，是否继续打印？",
        "ERROR: Printer support material shortage,still continue?": "错误：支撑材料不足，是否继续打印？",
        "ERROR: Nozzleheight set error</br>Correct range:": "错误：喷头高度设置错误</br>正确范围：",
        "Repeat last print?": "确定重复打印吗？",
        "ERROR: Other error ": "错误：其他错误 ",
        "Language test": "当前语言为中文",
        "Are you sure to stop the print job?": "确定停止打印吗？",
        "Found a new version": "发现新版本",
        ",download it immediately?": "，是否立即更新？",
        "[YES]: Update immediately": "[是]：立即更新",
        "[NO]: Remind me later": "[否]：下次通知我",
        "[CANCEL]: Switch off update reminder": "[取消]：不再提示更新",
        "Note: Download will be run in the background, after the completion of the notice": "注意：程序将在后台下载，完成后进行通知",
        "Update": "升级",
        "No new version": "无新版本",
        "ERROR: The model is opening, please try again later": "错误：正在读取模型，请稍后再试",
        "ERROR: Temperature is too high": "错误：温度过高",
        "ERROR: Sensor not connected": "传感器未连接",
        "ERROR: Calibration failure": "错误：校准失败",
        "ERROR: Printer is busy": "错误：系统正忙",
        "Success，Please reset nozzle height before printing": "调平成功，请重新设置喷头高度后进行打印",
        "ERROR: Printer error": "错误：打印机错误",
        "Print: ": "打印时间：",
        "Material: ": "耗费材料：",
        "g": "克",
        "H": "小时",
        "M": "分钟",
        "S": "秒",
        "ERROR: Templete directory get error": "错误：临时文件路径获取失败",
        "ERROR: Create dir error": "错误：创建目录失败",
        "ERROR: Copy UpdateFile Error_APP": "错误：拷贝升级程序失败_APP",
        "ERROR: Copy UpdateFile Error_DLL": "错误：拷贝升级程序失败_DLL",
        "ERROR: Nozzleheight set error": "错误：喷头高度设置错误",
        "ERROR:Model does not exist": "错误：模型不存在",
        "Activation": "激活",
        "Please activate the printer in time to use the full printer functions": "请及时激活打印机从而使用完整的打印机功能",
        "Activation state error, need to return to the factory": "激活状态错误，请返厂",
        "OK": "确定",
        "CANCEL": "取消",
        "YES": "是",
        "NO": "否",
        "ABORT": "退出",
        "RETRY": "重试",
        "IGNORE": "忽略",
        "Save successful": "保存成功",
        "Save failed": "保存失败",
        "Downloading, please wait": "正在下载，请稍等片刻",
        ",upgrade now?": ",立刻升级？",
        "Level data save error": "调平数据保存错误",
        "ERROR: Printer no response": "错误：打印机无响应",
        "ERROR: Printer password error": "错误：密码错误",
        "ERROR: Printer connected by other clients": "错误：打印机被占用",
        "ERROR: Printer none certification": "错误：打印机未认证",
        "Connection OK": "连接成功",
        "Connection Error": "连接失败",
        "Activation is successful, please restart the printer": "激活成功，请重新启动打印机",
        "Can not Save more than 4 millon facets model": "不能保存超过400万面片的模型",
        "No Model Selected": "没有选中的模型",
        "warning!": "警告!",
        "    Delete Selected Model?": "    是否删除选中模型?",
        "    Delete All Models?": "    是否删除全部模型?",
        "Please close the front door": "请关闭前门",
        "Model is too large! Can not Load": "模型过大！不能导入！",
        "Loading Failed": "模型载入失败！",
        "Print job stopped at ": "打印任务停在第",
        "th layer, resume the print?": "层，是否恢复打印?",
        "ERROR: Can't resume the broken print job": "错误：恢复打印失败",
        "ERROR: Data transfer failed, try again?": "错误：数据传输失败，是否重试？",
        "OpenGL Version Too Low! Check your Graphic Drivers!": "OpenGL 版本过低，请更新显卡驱动",
        "ERROR: Printer SN Error": "错误：打印机序列号有问题",
        "ERROR: Unknow error": "错误：未知错误",
        "ERROR: Invalide activekey": "错误：激活码错误",
        "ERROR: No factory actived": "错误：不是工厂激活状态",
        "ERROR: Active error,wrong key": "错误：激活失败，错误的激活码",
        "ERROR: The server returns the activation code to parse the JSON failed": "错误：服务器返回信息解析JSON失败",
        "ERROR: The server failed to return the activation code": "错误：从服务器返回激活码失败",
        "ERROR: Failed to get the check code from the printer": "错误：从打印机得到校验码失败",
        "ERROR: The current state of activation is not factory activation": "错误：当前的激活状态不是工厂激活",
        "ERROR: Failed to obtain an active state": "错误：获得激活状态失败",
        "ERROR: Model out of print bound": "错误：模型超出打印范围",
        "ERROR: Calibration Failure": "错误：校准失败",
        "ERROR: Server connection failed": "错误：服务器连接失败",
        "ERROR: Verification Failed,Please download activation package": "错误: 校验失败，请下载校验文件",
        "[YES] Perf Board\r\n[NO] Flex Board": "[是] 多孔板\r\n[否] Flex板",
        "Please Select The Type Of Plat": "请选择底板类型",
        "ERROR: Temperature is low": "错误：喷头温度低",
        "Do you want to keep current model?": "是否保留当前模型?"
    },
    "graphic": {
        "Filepath: ": "文件路径: ",
        "Size(mm): ": "模型尺寸: ",
        "Min-Size(mm): ": "最小位置: ",
        "Max-Size(mm): ": "最大位置: ",
        "Vertex Number: ": "顶点数目: ",
        "Facet Number: ": "面片数目: ",
        "Volume: ": "体积: ",
        "Copying...":"模型复制中，请等待...",
        "Saveing...":"模型保存中，请等待...",
        "has scaled from inch unit to mm unit!":"已由英寸转为毫米",
        "Property":"属性",
        "Copy": "复制",
        "1 model": "1个模型",
        "2 model": "2个模型",
        "5 model": "5个模型",
        "Delete": "删除",
        "Delete All": "全部删除",
        "Select All": "全部选择",
        "UnSelect All": "全不选择",
        "Initialize View": "复原视图",
        "Rotate By Models Center": "绕模型中心旋转",
        "Exit": "退出"
    },
    "image_front": {
        "_Model_Height":"模型高度",
        "_Base_Height":"基底高度",
        "_Style":"风格",
        "_Model_Size":"模型大小",
        "_Unit":"单位(mm)",
        "_Pen_Size":"画笔大小",
        "_Pen_Color":"画笔颜色",
        "_Pen_Type":"画笔种类",
        "_Erase_Size":"橡皮擦大小",
        "_Font":"字体",
        "_Font_Size":"文字大小",
        "_Font_Color":"文字颜色",
        "_Constrain":"等比例",
        "_Tools":"工具",
        "_Setting":"设置",
        "_Previous":"上一步",
        "_Apply":"应用"
    },
    "image": { }
}